"use client";

import { useHubDisplay } from "@/components/hub/HubOrganizationContext";

import { CheckCircle2 } from "lucide-react";
import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import { hubUi } from "@/components/hub/styles";


type Wallet = { availableBalanceCents: number; pendingCents: number };
function parseCents(value: string) { return Number(value.replace(/\D/g, "") || "0"); }
export default function AtlasHubRequestPage() {
  const { money } = useHubDisplay();
  const [wallet, setWallet] = useState<Wallet | null>(null); const [amount, setAmount] = useState(""); const [reason, setReason] = useState(""); const [confirming, setConfirming] = useState(false); const [saving, setSaving] = useState(false); const [success, setSuccess] = useState(false); const [error, setError] = useState(""); const idempotencyKey = useRef(crypto.randomUUID()); const amountCents = parseCents(amount);
  useEffect(() => { fetch("/api/hub/wallet/me", { cache: "no-store" }).then(async (response) => ({ response, data: await response.json() })).then(({ response, data }) => { if (!response.ok) throw new Error(data.error); setWallet(data); }).catch((reason) => setError(reason instanceof Error ? reason.message : "Erro ao carregar saldo.")); }, []);
  function validate() { if (!wallet) return "Aguarde o saldo ser carregado."; if (!Number.isSafeInteger(amountCents) || amountCents <= 0) return "Informe um valor maior que zero."; if (amountCents > wallet.availableBalanceCents) return "O valor supera seu saldo disponível."; if (reason.trim().length < 5 || reason.trim().length > 500) return "A justificativa deve ter entre 5 e 500 caracteres."; return ""; }
  async function submit() { if (saving) return; const issue = validate(); if (issue) { setError(issue); setConfirming(false); return; } setSaving(true); setError(""); try { const response = await fetch("/api/hub/wallet/me/requests", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ amountCents, reason: reason.trim(), idempotencyKey: idempotencyKey.current }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Não foi possível criar a solicitação."); setSuccess(true); setConfirming(false); } catch (reasonValue) { setError(reasonValue instanceof Error ? reasonValue.message : "Erro ao enviar."); } finally { setSaving(false); } }
  if (success) return <div className={`${hubUi.page} max-w-2xl`}><section className={`${hubUi.panel} p-8 text-center`}><CheckCircle2 className="mx-auto h-10 w-10 text-green-700" /><h1 className="mt-4 text-2xl font-semibold">Solicitação enviada</h1><p className="mt-2 text-sm text-zinc-600">O pedido de {money(amountCents)} foi registrado e aguarda revisão.</p><div className="mt-6 flex flex-col justify-center gap-3 sm:flex-row"><Link href="/hub/carteira" className={hubUi.primaryButton}>Ver minha carteira</Link><Link href="/hub/carteira/extrato" className={hubUi.secondaryButton}>Ver extrato</Link></div></section></div>;
  return <div className={`${hubUi.page} max-w-2xl`}><header><h1 className="text-2xl font-semibold">Solicitar gasto</h1><p className="mt-1 text-sm text-zinc-600">Reserve parte do seu saldo para uma despesa.</p></header><section className="grid gap-3 sm:grid-cols-2"><div className="rounded-2xl bg-black p-5 text-white"><p className="text-xs text-zinc-400">Saldo disponível</p><p className="mt-2 break-words text-2xl font-semibold">{wallet ? money(wallet.availableBalanceCents) : "—"}</p></div><div className={`${hubUi.panel} p-5`}><p className="text-xs text-zinc-500">Já solicitado</p><p className="mt-2 break-words text-2xl font-semibold">{wallet ? money(wallet.pendingCents) : "—"}</p></div></section><form onSubmit={(event) => { event.preventDefault(); const issue = validate(); if (issue) setError(issue); else { setError(""); setConfirming(true); } }} className={`${hubUi.panel} space-y-5 p-5 sm:p-6`}><div><label htmlFor="request-amount" className="mb-1.5 block text-sm font-medium">Valor</label><input id="request-amount" inputMode="numeric" value={amount} onChange={(event) => setAmount(money(parseCents(event.target.value)))} placeholder={money(0)} className={hubUi.input} /></div><div><label htmlFor="request-reason" className="mb-1.5 block text-sm font-medium">Justificativa</label><textarea id="request-reason" value={reason} onChange={(event) => setReason(event.target.value)} maxLength={500} rows={4} className={hubUi.input} /><p className="mt-1 text-right text-xs text-zinc-500">{reason.length}/500</p></div>{error ? <p role="alert" className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-800">{error}</p> : null}<button disabled={!wallet || saving} className={hubUi.primaryButton}>Revisar solicitação</button></form>{confirming ? <div className="fixed inset-0 z-50 flex items-end justify-center bg-black/50 p-4 sm:items-center" role="dialog" aria-modal="true" aria-labelledby="request-confirm-title"><div className="w-full max-w-md rounded-2xl bg-white p-6"><h2 id="request-confirm-title" className="text-lg font-semibold">Confirmar solicitação</h2><dl className="mt-4 space-y-3 text-sm"><div className="flex justify-between gap-4"><dt className="text-zinc-500">Valor</dt><dd className="font-semibold">{money(amountCents)}</dd></div><div><dt className="text-zinc-500">Justificativa</dt><dd className="mt-1 break-words">{reason.trim()}</dd></div></dl><div className="mt-6 flex flex-col-reverse gap-2 sm:flex-row sm:justify-end"><button type="button" onClick={() => setConfirming(false)} className={hubUi.secondaryButton}>Voltar</button><button type="button" onClick={() => void submit()} disabled={saving} className={hubUi.primaryButton}>{saving ? "Enviando..." : "Confirmar"}</button></div></div></div> : null}</div>;
}
