"use client";

import { useHubDisplay } from "@/components/hub/HubOrganizationContext";

import { Camera, ShieldCheck } from "lucide-react";
import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import { UserAvatar } from "@/components/UserAvatar";
import { hubUi } from "@/components/hub/styles";
import { hubMemberStatusLabel, hubRoleLabel } from "@/lib/hub/display";

type Member = { id: string; name: string; email: string; role: string; status: string; avatarUrl: string | null; lastLoginAt: string | null; createdAt: string; directorate: { name: string } | null };
export default function AtlasHubAccountPage() {
  const { dateTime } = useHubDisplay();
  const [member, setMember] = useState<Member | null>(null); const [name, setName] = useState(""); const [editing, setEditing] = useState(false); const [saving, setSaving] = useState(false); const [uploading, setUploading] = useState(false); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const fileRef = useRef<HTMLInputElement>(null);
  async function load() { setError(""); try { const response = await fetch("/api/hub/me/profile", { cache: "no-store" }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Não foi possível carregar o perfil."); setMember(data.member); setName(data.member.name); } catch (reason) { setError(reason instanceof Error ? reason.message : "Erro ao carregar."); } }
  useEffect(() => { void load(); }, []);
  async function save() { setSaving(true); setError(""); setMessage(""); try { const response = await fetch("/api/hub/me/profile", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Não foi possível salvar."); setMember(data.member); setEditing(false); setMessage("Perfil atualizado."); } catch (reason) { setError(reason instanceof Error ? reason.message : "Erro ao salvar."); } finally { setSaving(false); } }
  async function upload(event: React.ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file) return; if (!["image/jpeg", "image/png", "image/webp"].includes(file.type) || file.size > 3 * 1024 * 1024) { setError("Envie uma imagem JPG, PNG ou WEBP de até 3 MB."); return; } setUploading(true); setError(""); const form = new FormData(); form.append("avatar", file); try { const response = await fetch("/api/hub/me/avatar", { method: "POST", body: form }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Não foi possível enviar a imagem."); setMember((current) => current ? { ...current, avatarUrl: data.avatarUrl } : current); setMessage("Foto atualizada."); } catch (reason) { setError(reason instanceof Error ? reason.message : "Erro no envio."); } finally { setUploading(false); event.target.value = ""; } }
  if (!member && !error) return <div className={`${hubUi.page} max-w-3xl animate-pulse`}><div className="h-56 rounded-2xl bg-white" /></div>;
  return <div className={`${hubUi.page} max-w-3xl`}><header><h1 className="text-2xl font-semibold">Minha conta</h1><p className="mt-1 text-sm text-zinc-600">Perfil e segurança do seu acesso.</p></header>{error ? <div role="alert" className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-800">{error}</div> : null}{message ? <div role="status" className="rounded-xl border border-green-200 bg-green-50 p-3 text-sm text-green-800">{message}</div> : null}{member ? <><section className={`${hubUi.panel} p-5 sm:p-6`}><div className="flex flex-col gap-5 sm:flex-row sm:items-center"><div className="relative w-fit"><UserAvatar name={member.name} src={member.avatarUrl || undefined} size="lg" /><button type="button" onClick={() => fileRef.current?.click()} disabled={uploading} aria-label="Alterar foto" className="absolute -bottom-1 -right-1 flex h-9 w-9 items-center justify-center rounded-full border-2 border-white bg-black text-white"><Camera className="h-4 w-4" /></button><input ref={fileRef} type="file" accept="image/jpeg,image/png,image/webp" onChange={upload} className="sr-only" /></div><div className="min-w-0"><h2 className="break-words text-xl font-semibold">{member.name}</h2><p className="break-all text-sm text-zinc-500">{member.email}</p><p className="mt-2 text-xs text-zinc-500">{hubRoleLabel(member.role)} · {hubMemberStatusLabel(member.status)} · {member.directorate?.name || "Sem diretoria"}</p></div></div><div className="mt-6 border-t border-zinc-200 pt-5"><label htmlFor="profile-name" className="mb-1.5 block text-sm font-medium">Nome</label><input id="profile-name" value={name} onChange={(event) => setName(event.target.value)} disabled={!editing} className={hubUi.input} /><div className="mt-4 flex flex-wrap gap-2">{editing ? <><button type="button" onClick={() => void save()} disabled={saving} className={hubUi.primaryButton}>{saving ? "Salvando..." : "Salvar"}</button><button type="button" onClick={() => { setEditing(false); setName(member.name); }} className={hubUi.secondaryButton}>Cancelar</button></> : <button type="button" onClick={() => setEditing(true)} className={hubUi.secondaryButton}>Editar nome</button>}</div></div></section><section className={`${hubUi.panel} p-5 sm:p-6`}><div className="flex items-start gap-3"><ShieldCheck className="mt-0.5 h-5 w-5" /><div><h2 className="font-semibold">Segurança</h2><p className="mt-1 text-sm text-zinc-600">Último acesso: {member.lastLoginAt ? dateTime(member.lastLoginAt) : "ainda não registrado"}.</p><Link href="/hub/alterar-senha" className={`${hubUi.secondaryButton} mt-4`}>Alterar senha</Link></div></div></section></> : <div className={`${hubUi.panel} p-8 text-center`}><button type="button" onClick={() => void load()} className={hubUi.secondaryButton}>Tentar novamente</button></div>}</div>;
}
