import assert from "node:assert/strict";
import test, { after, before } from "node:test";
import { PrismaClient, type HubRole } from "@prisma/client";
import { assertOrganizationRetainsActiveSuperAdmin } from "./member-management";
import { hasHubPermission } from "./permissions";
import {
  approveFinancialEntry, assignOnboarding, assessCompetency, completeOnboardingItem, createBudget,
  createCandidate, createFeedback, createFinancialEntry, createRecognition, createRecruitmentProcess,
  createReimbursement, getBudgetReport, getMemberProfile, hireCandidate, moveCandidateStage,
  recordSettlement, reverseSettlement, reviewReimbursement, setFinancialPeriodStatus, submitEvaluation,
  submitFinancialEntry, submitReimbursement, updateDevelopmentGoal, updateManagedProfile, updateOwnProfile,
} from "./operations-service";

const databaseUrl = process.env.ATLAS_HUB_TEST_DATABASE_URL;
if (!databaseUrl) throw new Error("ATLAS_HUB_TEST_DATABASE_URL e obrigatoria para os testes operacionais.");
else {
  const prisma = new PrismaClient({ datasourceUrl: databaseUrl });
  const tag = `ops-req-${Date.now()}-${Math.random().toString(36).slice(2)}`;
  let orgA = "", orgB = "", dirA = "", dirB = "", admin = "", admin2 = "", finance = "", director = "", member = "", other = "", foreignMember = "", category = "", foreignCategory = "", costCenter = "", foreignCostCenter = "", foreignCounterparty = "";
  const actor = (id: string, role: HubRole, organizationId = orgA, directorateId: string | null = null) => ({ id, organizationId, role, directorateId });
  const expectStatus = (status: number) => (error: unknown) => (error as { status?: number }).status === status;
  const entryInput = (key: string, overrides: Partial<Parameters<typeof createFinancialEntry>[2]> = {}) => ({ direction: "PAYABLE" as const, description: "Operacao de teste", categoryId: category, issueDate: new Date("2040-01-10T12:00:00Z"), competenceDate: new Date("2040-01-10T12:00:00Z"), totalCents: 1000, installments: [{ amountCents: 1000, dueDate: new Date("2040-01-20T12:00:00Z") }], idempotencyKey: `${tag}-${key}`, ...overrides });
  async function approvedEntry(key: string, amount = 1000) { const entry = await createFinancialEntry(prisma, actor(admin, "ADMIN"), entryInput(key, { totalCents: amount, installments: [{ amountCents: amount, dueDate: new Date("2040-01-20T12:00:00Z") }] })); await submitFinancialEntry(prisma, actor(admin, "ADMIN"), entry.id); await approveFinancialEntry(prisma, actor(finance, "FINANCE"), entry.id); const installment = await prisma.hubFinancialInstallment.findFirstOrThrow({ where: { entryId: entry.id } }); return { entry, installment }; }

  before(async () => {
    const [a, b] = await Promise.all([prisma.hubOrganization.create({ data: { name: `${tag}-a`, hubName: tag, slug: `${tag}-a` } }), prisma.hubOrganization.create({ data: { name: `${tag}-b`, hubName: tag, slug: `${tag}-b` } })]); orgA = a.id; orgB = b.id;
    const [d1, d2] = await Promise.all([prisma.hubDirectorate.create({ data: { organizationId: orgA, name: "Produto", slug: `${tag}-produto` } }), prisma.hubDirectorate.create({ data: { organizationId: orgA, name: "Comercial", slug: `${tag}-comercial` } })]); dirA = d1.id; dirB = d2.id;
    const make = (organizationId: string, name: string, role: HubRole, directorateId: string | null = null) => prisma.hubMember.create({ data: { organizationId, email: `${tag}-${name.toLowerCase()}@test.local`, normalizedEmail: `${tag}-${name.toLowerCase()}@test.local`, name, passwordHash: "test", role, status: "ACTIVE", mustChangePassword: false, directorateId } });
    const members = await Promise.all([make(orgA, "Admin", "ADMIN"), make(orgA, "Admin2", "ADMIN"), make(orgA, "Finance", "FINANCE"), make(orgA, "Director", "DIRECTOR", dirA), make(orgA, "Member", "MEMBER", dirA), make(orgA, "Other", "MEMBER", dirB), make(orgB, "Foreign", "MEMBER")]); [admin, admin2, finance, director, member, other, foreignMember] = members.map((item) => item.id);
    await prisma.hubWalletAccount.createMany({ data: members.map((item, index) => ({ memberId: item.id, balanceCents: index === 4 ? 777 : 0 })) });
    const [catA, catB] = await Promise.all([prisma.hubFinancialCategory.create({ data: { organizationId: orgA, name: "Servicos", normalizedName: `${tag}-cat-a`, type: "BOTH" } }), prisma.hubFinancialCategory.create({ data: { organizationId: orgB, name: "Foreign", normalizedName: `${tag}-cat-b`, type: "BOTH" } })]); category = catA.id; foreignCategory = catB.id;
    const [ccA, ccB] = await Promise.all([prisma.hubCostCenter.create({ data: { organizationId: orgA, directorateId: dirA, name: "Produto", normalizedName: `${tag}-cc-a`, code: `${tag}-A`, normalizedCode: `${tag}-a` } }), prisma.hubCostCenter.create({ data: { organizationId: orgB, name: "Foreign", normalizedName: `${tag}-cc-b`, code: `${tag}-B`, normalizedCode: `${tag}-b` } })]); costCenter = ccA.id; foreignCostCenter = ccB.id;
    const [, cpB] = await Promise.all([prisma.hubCounterparty.create({ data: { organizationId: orgA, name: "Fornecedor", normalizedName: `${tag}-cp-a`, type: "SUPPLIER" } }), prisma.hubCounterparty.create({ data: { organizationId: orgB, name: "Foreign", normalizedName: `${tag}-cp-b`, type: "OTHER" } })]); foreignCounterparty = cpB.id;
    await prisma.hubProject.create({ data: { organizationId: orgA, title: `${tag}-project`, grossAmountCents: 12345, status: "APPROVED", createdById: admin } });
  });
  after(async () => prisma.$disconnect());

  test("01 financial category isolation", async () => { await assert.rejects(() => createFinancialEntry(prisma, actor(admin, "ADMIN"), entryInput("foreign-category", { categoryId: foreignCategory })), expectStatus(404)); });
  test("02 cost-center isolation", async () => { await assert.rejects(() => createFinancialEntry(prisma, actor(admin, "ADMIN"), entryInput("foreign-center", { costCenterId: foreignCostCenter })), expectStatus(404)); });
  test("03 counterparty isolation", async () => { await assert.rejects(() => createFinancialEntry(prisma, actor(admin, "ADMIN"), entryInput("foreign-counterparty", { counterpartyId: foreignCounterparty })), expectStatus(404)); });
  test("04 entry idempotency", async () => { const first = await createFinancialEntry(prisma, actor(admin, "ADMIN"), entryInput("idempotent")); const retry = await createFinancialEntry(prisma, actor(admin, "ADMIN"), entryInput("idempotent")); assert.equal(retry.id, first.id); });
  test("05 key reuse with different payload", async () => { await createFinancialEntry(prisma, actor(admin, "ADMIN"), entryInput("hash")); await assert.rejects(() => createFinancialEntry(prisma, actor(admin, "ADMIN"), entryInput("hash", { description: "Outro payload" })), expectStatus(409)); });
  test("06 self-approval rejection", async () => { const created = await createFinancialEntry(prisma, actor(admin, "ADMIN"), entryInput("self-approval")); await submitFinancialEntry(prisma, actor(admin, "ADMIN"), created.id); await assert.rejects(() => approveFinancialEntry(prisma, actor(admin, "ADMIN"), created.id), expectStatus(403)); });
  test("07 approval race", async () => { const created = await createFinancialEntry(prisma, actor(admin, "ADMIN"), entryInput("approval-race")); await submitFinancialEntry(prisma, actor(admin, "ADMIN"), created.id); const results = await Promise.allSettled([approveFinancialEntry(prisma, actor(finance, "FINANCE"), created.id), approveFinancialEntry(prisma, actor(admin2, "ADMIN"), created.id)]); assert.equal(results.filter((item) => item.status === "fulfilled").length, 1); assert.equal((await prisma.hubFinancialEntry.findUniqueOrThrow({ where: { id: created.id } })).status, "APPROVED"); });
  test("08 installment sum validation", async () => { await assert.rejects(() => createFinancialEntry(prisma, actor(admin, "ADMIN"), entryInput("bad-sum", { installments: [{ amountCents: 999, dueDate: new Date() }] })), expectStatus(400)); });
  test("09 partial settlement", async () => { const { entry, installment } = await approvedEntry("partial"); await recordSettlement(prisma, actor(finance, "FINANCE"), entry.id, { installmentId: installment.id, amountCents: 400, settledAt: new Date("2040-01-15T12:00:00Z"), method: "PIX", idempotencyKey: `${tag}-partial-settle` }); assert.equal((await prisma.hubFinancialEntry.findUniqueOrThrow({ where: { id: entry.id } })).status, "PARTIALLY_SETTLED"); });
  test("10 excessive settlement rejection", async () => { const { entry, installment } = await approvedEntry("excess"); await assert.rejects(() => recordSettlement(prisma, actor(finance, "FINANCE"), entry.id, { installmentId: installment.id, amountCents: 1001, settledAt: new Date("2040-01-15T12:00:00Z"), method: "PIX", idempotencyKey: `${tag}-excess-settle` }), expectStatus(409)); });
  test("11 simultaneous settlement race", async () => { const { entry, installment } = await approvedEntry("settlement-race"); const results = await Promise.allSettled([recordSettlement(prisma, actor(finance, "FINANCE"), entry.id, { installmentId: installment.id, amountCents: 700, settledAt: new Date("2040-01-15T12:00:00Z"), method: "PIX", idempotencyKey: `${tag}-race-a` }), recordSettlement(prisma, actor(admin2, "ADMIN"), entry.id, { installmentId: installment.id, amountCents: 700, settledAt: new Date("2040-01-15T12:00:00Z"), method: "CASH", idempotencyKey: `${tag}-race-b` })]); assert.equal(results.filter((item) => item.status === "fulfilled").length, 1); const sum = await prisma.hubFinancialSettlement.aggregate({ where: { entryId: entry.id, reversedAt: null }, _sum: { amountCents: true } }); assert.ok((sum._sum.amountCents || 0) <= 1000); });
  test("12 settlement reversal", async () => { const { entry, installment } = await approvedEntry("reversal"); const settlement = await recordSettlement(prisma, actor(finance, "FINANCE"), entry.id, { installmentId: installment.id, amountCents: 500, settledAt: new Date("2040-02-15T12:00:00Z"), method: "PIX", idempotencyKey: `${tag}-reversal-settle` }); await reverseSettlement(prisma, actor(finance, "FINANCE"), settlement.id, "Estorno confirmado"); assert.equal(await prisma.hubFinancialSettlement.count({ where: { id: settlement.id, reversedAt: { not: null } } }), 1); });
  test("13 closed-period mutation rejection", async () => { const { entry, installment } = await approvedEntry("closed-period"); await setFinancialPeriodStatus(prisma, actor(finance, "FINANCE"), { year: 2040, month: 3, status: "CLOSED" }); await assert.rejects(() => recordSettlement(prisma, actor(finance, "FINANCE"), entry.id, { installmentId: installment.id, amountCents: 100, settledAt: new Date("2040-03-15T12:00:00Z"), method: "PIX", idempotencyKey: `${tag}-closed-settle` }), expectStatus(409)); });
  test("14 controlled period reopening", async () => { await assert.rejects(() => setFinancialPeriodStatus(prisma, actor(finance, "FINANCE"), { year: 2040, month: 3, status: "OPEN" }), expectStatus(400)); const period = await setFinancialPeriodStatus(prisma, actor(finance, "FINANCE"), { year: 2040, month: 3, status: "OPEN", reason: "Ajuste aprovado" }); assert.equal(period.status, "OPEN"); assert.equal(period.reopenReason, "Ajuste aprovado"); });
  test("15 budget isolation", async () => { const foreignBudget = await prisma.hubBudget.create({ data: { organizationId: orgB, name: `${tag}-foreign`, year: 2041, createdById: foreignMember } }); await assert.rejects(() => getBudgetReport(prisma, actor(finance, "FINANCE"), foreignBudget.id), expectStatus(404)); });
  test("16 budget actual calculation", async () => { const budget = await createBudget(prisma, actor(finance, "FINANCE"), { name: `${tag}-budget`, year: 2041, lines: [{ categoryId: category, costCenterId: costCenter, month: 1, plannedCents: 1500 }] }); await prisma.hubBudget.update({ where: { id: budget.id }, data: { status: "APPROVED" } }); const { entry, installment } = await approvedEntry("budget-actual", 500); await prisma.hubFinancialEntry.update({ where: { id: entry.id }, data: { costCenterId: costCenter } }); await recordSettlement(prisma, actor(finance, "FINANCE"), entry.id, { installmentId: installment.id, amountCents: 500, settledAt: new Date("2041-01-15T12:00:00Z"), method: "PIX", idempotencyKey: `${tag}-budget-settle` }); const report = await getBudgetReport(prisma, actor(finance, "FINANCE"), budget.id); assert.equal(report.lines[0].actualCents, 500); assert.equal(report.lines[0].varianceCents, 1000); });
  test("17 reimbursement ownership", async () => { const request = await createReimbursement(prisma, actor(member, "MEMBER", orgA, dirA), { description: "Taxi", items: [{ description: "Corrida", expenseDate: new Date(), amountCents: 100, categoryId: category }], idempotencyKey: `${tag}-reimb-owner` }); await assert.rejects(() => submitReimbursement(prisma, actor(other, "MEMBER", orgA, dirB), request.id), expectStatus(403)); });
  test("18 reimbursement self-review rejection", async () => { const request = await createReimbursement(prisma, actor(member, "MEMBER", orgA, dirA), { description: "Taxi", items: [{ description: "Corrida", expenseDate: new Date(), amountCents: 100, categoryId: category }], idempotencyKey: `${tag}-reimb-self` }); await submitReimbursement(prisma, actor(member, "MEMBER", orgA, dirA), request.id); await assert.rejects(() => reviewReimbursement(prisma, actor(member, "MEMBER", orgA, dirA), request.id, { decision: "APPROVE" }), expectStatus(403)); });
  test("19 reimbursement approval creates one payable entry", async () => { const request = await createReimbursement(prisma, actor(member, "MEMBER", orgA, dirA), { description: "Taxi", items: [{ description: "Corrida", expenseDate: new Date(), amountCents: 200, categoryId: category }], idempotencyKey: `${tag}-reimb-one-entry` }); await submitReimbursement(prisma, actor(member, "MEMBER", orgA, dirA), request.id); await reviewReimbursement(prisma, actor(finance, "FINANCE"), request.id, { decision: "APPROVE" }); assert.equal(await prisma.hubFinancialEntry.count({ where: { organizationId: orgA, idempotencyKey: `reimbursement:${request.id}` } }), 1); });
  test("20 reimbursement payment consistency", async () => { const request = await createReimbursement(prisma, actor(member, "MEMBER", orgA, dirA), { description: "Hospedagem", items: [{ description: "Diaria", expenseDate: new Date(), amountCents: 300, categoryId: category }], idempotencyKey: `${tag}-reimb-paid` }); await submitReimbursement(prisma, actor(member, "MEMBER", orgA, dirA), request.id); const approved = await reviewReimbursement(prisma, actor(finance, "FINANCE"), request.id, { decision: "APPROVE" }); const installment = await prisma.hubFinancialInstallment.findFirstOrThrow({ where: { entryId: approved.financialEntryId! } }); const settlement = await recordSettlement(prisma, actor(finance, "FINANCE"), approved.financialEntryId!, { installmentId: installment.id, amountCents: 300, settledAt: new Date(), method: "PIX", idempotencyKey: `${tag}-reimb-payment` }); assert.equal((await prisma.hubReimbursementRequest.findUniqueOrThrow({ where: { id: request.id } })).status, "PAID"); await reverseSettlement(prisma, actor(finance, "FINANCE"), settlement.id, "Pagamento revertido"); assert.equal((await prisma.hubReimbursementRequest.findUniqueOrThrow({ where: { id: request.id } })).status, "APPROVED"); });
  test("21 wallet balances unchanged", async () => { assert.equal((await prisma.hubWalletAccount.findUniqueOrThrow({ where: { memberId: member } })).balanceCents, 777); });
  test("22 project payouts unchanged", async () => { const project = await prisma.hubProject.findFirstOrThrow({ where: { organizationId: orgA, title: `${tag}-project` } }); assert.equal(project.grossAmountCents, 12345); assert.equal(project.status, "APPROVED"); });
  test("23 CSV authorization", async () => { const roles = await prisma.hubMember.findMany({ where: { id: { in: [finance, member] } }, select: { id: true, role: true } }); assert.equal(hasHubPermission(roles.find((item) => item.id === finance)!.role, "finance:reports"), true); assert.equal(hasHubPermission(roles.find((item) => item.id === member)!.role, "finance:reports"), false); });
  test("24 profile isolation", async () => { await assert.rejects(() => getMemberProfile(prisma, actor(member, "MEMBER", orgA, dirA), foreignMember), expectStatus(404)); });
  test("25 sensitive-field authorization", async () => { await updateManagedProfile(prisma, actor(admin, "ADMIN"), member, { emergencyContactName: "Contato privado", emergencyContactPhone: "85999999999" }); const result = await getMemberProfile(prisma, actor(member, "MEMBER", orgA, dirA), member); assert.equal(Object.prototype.hasOwnProperty.call(result.profile || {}, "emergencyContactName"), false); });
  test("26 self-profile field limits", async () => { await updateOwnProfile(prisma, actor(member, "MEMBER", orgA, dirA), { phone: "111", bio: "Publica" }); const stored = await prisma.hubMemberProfile.findUniqueOrThrow({ where: { memberId: member } }); assert.equal(stored.emergencyContactName, "Contato privado"); assert.equal(stored.phone, "111"); });
  test("27 director own-directorate policy", async () => { const result = await getMemberProfile(prisma, actor(director, "DIRECTOR", orgA, dirA), member); assert.equal(result.member.id, member); });
  test("28 director cross-directorate rejection", async () => { await assert.rejects(() => getMemberProfile(prisma, actor(director, "DIRECTOR", orgA, dirA), other), expectStatus(403)); });
  let onboardingItemId = "";
  test("29 onboarding assignment", async () => { const template = await prisma.hubOnboardingTemplate.create({ data: { organizationId: orgA, directorateId: dirA, name: `${tag}-onboarding`, createdById: admin } }); await prisma.hubOnboardingTemplateItem.create({ data: { organizationId: orgA, templateId: template.id, title: "Ler manual", order: 1 } }); const assignment = await assignOnboarding(prisma, actor(director, "DIRECTOR", orgA, dirA), { templateId: template.id, memberId: member }); onboardingItemId = (await prisma.hubOnboardingAssignmentItem.findFirstOrThrow({ where: { assignmentId: assignment.id } })).id; assert.ok(onboardingItemId); });
  test("30 onboarding completion race", async () => { const results = await Promise.allSettled([completeOnboardingItem(prisma, actor(member, "MEMBER", orgA, dirA), onboardingItemId, 1), completeOnboardingItem(prisma, actor(member, "MEMBER", orgA, dirA), onboardingItemId, 1)]); assert.equal(results.filter((item) => item.status === "fulfilled").length, 1); });
  test("31 lifecycle append-only behavior", async () => { await prisma.hubMemberLifecycleEvent.createMany({ data: [{ organizationId: orgA, memberId: member, type: "ROLE_CHANGED", recordedById: admin }, { organizationId: orgA, memberId: member, type: "DIRECTORATE_CHANGED", recordedById: admin }] }); assert.equal(await prisma.hubMemberLifecycleEvent.count({ where: { organizationId: orgA, memberId: member } }), 2); });
  test("32 offboarding preserves history", async () => { const before = await prisma.hubMemberLifecycleEvent.count({ where: { organizationId: orgA, memberId: other } }); await prisma.$transaction(async (tx) => { await tx.hubMember.update({ where: { id: other }, data: { status: "DISABLED" } }); await tx.hubMemberLifecycleEvent.create({ data: { organizationId: orgA, memberId: other, type: "OFFBOARDED", recordedById: admin } }); }); assert.equal(await prisma.hubMemberLifecycleEvent.count({ where: { organizationId: orgA, memberId: other } }), before + 1); assert.equal(await prisma.hubProject.count({ where: { organizationId: orgA } }), 1); });
  test("33 last-super-admin protection", async () => { const org = await prisma.hubOrganization.create({ data: { name: `${tag}-super`, hubName: tag, slug: `${tag}-super` } }); await prisma.hubMember.create({ data: { organizationId: org.id, email: `${tag}-super@test.local`, normalizedEmail: `${tag}-super@test.local`, name: "Super", passwordHash: "test", role: "SUPER_ADMIN", status: "ACTIVE" } }); await assert.rejects(() => prisma.$transaction((tx) => assertOrganizationRetainsActiveSuperAdmin(tx, { organizationId: org.id, currentRole: "SUPER_ADMIN", currentStatus: "ACTIVE", nextRole: "SUPER_ADMIN", nextStatus: "DISABLED" })), expectStatus(409)); });
  test("34 competency isolation", async () => { const competency = await prisma.hubCompetency.create({ data: { organizationId: orgB, name: "Foreign", normalizedName: `${tag}-foreign-competency` } }); await assert.rejects(() => assessCompetency(prisma, actor(admin, "ADMIN"), { memberId: member, competencyId: competency.id, level: 3 }), expectStatus(404)); });
  test("35 goal optimistic concurrency", async () => { const plan = await prisma.hubDevelopmentPlan.create({ data: { organizationId: orgA, memberId: member, title: "PDI", createdById: director } }); const goal = await prisma.hubDevelopmentGoal.create({ data: { organizationId: orgA, planId: plan.id, ownerMemberId: member, managerMemberId: director, title: "Meta", status: "ACTIVE" } }); await updateDevelopmentGoal(prisma, actor(director, "DIRECTOR", orgA, dirA), goal.id, { version: 1, progress: 50 }); await assert.rejects(() => updateDevelopmentGoal(prisma, actor(director, "DIRECTOR", orgA, dirA), goal.id, { version: 1, progress: 70 }), expectStatus(409)); });
  let cycleId = "", criterionId = "";
  test("36 feedback visibility", async () => { const feedback = await createFeedback(prisma, actor(director, "DIRECTOR", orgA, dirA), { recipientMemberId: member, body: "Conteudo confidencial", visibility: "PRIVATE_TO_RECIPIENT" }); const visibleToRecipient = await prisma.hubFeedback.count({ where: { id: feedback.id, organizationId: orgA, recipientMemberId: member } }); const visibleToOther = await prisma.hubFeedback.count({ where: { id: feedback.id, organizationId: orgA, OR: [{ recipientMemberId: other }, { authorMemberId: other }] } }); assert.equal(visibleToRecipient, 1); assert.equal(visibleToOther, 0); });
  test("37 closed-cycle immutability", async () => { const cycle = await prisma.hubPeopleCycle.create({ data: { organizationId: orgA, name: `${tag}-closed-cycle`, status: "CLOSED", createdById: admin } }); await assert.rejects(() => createFeedback(prisma, actor(director, "DIRECTOR", orgA, dirA), { recipientMemberId: member, body: "Nao deve entrar", visibility: "MANAGER_AND_RECIPIENT", cycleId: cycle.id }), expectStatus(409)); });
  test("38 evaluation ownership", async () => { const cycle = await prisma.hubPeopleCycle.create({ data: { organizationId: orgA, name: `${tag}-active-cycle`, status: "ACTIVE", createdById: admin } }); cycleId = cycle.id; criterionId = (await prisma.hubEvaluationCriterion.create({ data: { organizationId: orgA, cycleId, title: "Entrega", order: 1 } })).id; const evaluation = await prisma.hubEvaluation.create({ data: { organizationId: orgA, cycleId, evaluatorMemberId: member, evaluatedMemberId: member, type: "SELF" } }); await assert.rejects(() => submitEvaluation(prisma, actor(director, "DIRECTOR", orgA, dirA), evaluation.id, { version: 1, responses: [{ criterionId, score: 5 }] }), expectStatus(403)); });
  test("39 evaluation duplicate submission", async () => { const evaluation = await prisma.hubEvaluation.create({ data: { organizationId: orgA, cycleId, evaluatorMemberId: member, evaluatedMemberId: director, type: "PEER" } }); await submitEvaluation(prisma, actor(member, "MEMBER", orgA, dirA), evaluation.id, { version: 1, responses: [{ criterionId, score: 4, comment: "Privado" }] }); await assert.rejects(() => submitEvaluation(prisma, actor(member, "MEMBER", orgA, dirA), evaluation.id, { version: 2, responses: [{ criterionId, score: 4 }] }), expectStatus(409)); });
  test("40 recognition visibility", async () => { const recognition = await createRecognition(prisma, actor(director, "DIRECTOR", orgA, dirA), { recipientMemberId: member, title: "Destaque", description: "Entrega", visibility: "PRIVATE" }); assert.equal(await prisma.hubRecognition.count({ where: { id: recognition.id, OR: [{ recipientMemberId: member }, { givenById: member }] } }), 1); assert.equal(await prisma.hubRecognition.count({ where: { id: recognition.id, OR: [{ visibility: "ORGANIZATION" }, { recipientMemberId: other }, { givenById: other }] } }), 0); });
  test("41 recruitment-process isolation", async () => { const process = await prisma.hubRecruitmentProcess.create({ data: { organizationId: orgB, title: "Foreign", status: "OPEN", createdById: foreignMember } }); await assert.rejects(() => createCandidate(prisma, actor(admin, "ADMIN"), { processId: process.id, name: "Candidato", email: `${tag}-foreign-candidate@test.local` }), expectStatus(404)); });
  test("42 candidate data isolation", async () => { const process = await prisma.hubRecruitmentProcess.create({ data: { organizationId: orgB, title: "Foreign 2", status: "OPEN", createdById: foreignMember } }); const stage = await prisma.hubRecruitmentStage.create({ data: { organizationId: orgB, processId: process.id, name: "Triagem", order: 1 } }); const candidate = await prisma.hubCandidate.create({ data: { organizationId: orgB, processId: process.id, name: "Foreign", email: `${tag}-candidate-b@test.local`, normalizedEmail: `${tag}-candidate-b@test.local` } }); await assert.rejects(() => moveCandidateStage(prisma, actor(admin, "ADMIN"), candidate.id, { toStageId: stage.id, expectedVersion: 1, idempotencyKey: `${tag}-foreign-move` }), expectStatus(404)); });
  let candidateId = "";
  test("43 candidate stage append-only behavior", async () => { const process = await createRecruitmentProcess(prisma, actor(admin, "ADMIN"), { title: `${tag}-recruitment`, stages: ["Triagem", "Entrevista"] }); const stages = await prisma.hubRecruitmentStage.findMany({ where: { processId: process.id }, orderBy: { order: "asc" } }); const candidate = await createCandidate(prisma, actor(admin, "ADMIN"), { processId: process.id, name: "Candidato A", email: `${tag}-candidate-a@test.local` }); candidateId = candidate.id; await moveCandidateStage(prisma, actor(admin, "ADMIN"), candidate.id, { toStageId: stages[1].id, expectedVersion: 1, idempotencyKey: `${tag}-candidate-move` }); assert.equal(await prisma.hubCandidateStageEvent.count({ where: { candidateId: candidate.id } }), 2); });
  test("44 hiring explicit confirmation", async () => { const candidate = await prisma.hubCandidate.findUniqueOrThrow({ where: { id: candidateId } }); await assert.rejects(() => hireCandidate(prisma, actor(admin, "ADMIN"), candidate.id, { expectedVersion: candidate.version, confirm: false }), expectStatus(400)); const hired = await hireCandidate(prisma, actor(admin, "ADMIN"), candidate.id, { expectedVersion: candidate.version, confirm: true, directorateId: dirA }); assert.equal(hired.member.status, "INVITED"); assert.equal(await prisma.hubMember.count({ where: { id: hired.member.id, passwordHash: { startsWith: "!invited:" } } }), 1); });
  test("45 notification privacy", async () => { const bodies = (await prisma.hubNotification.findMany({ where: { organizationId: orgA }, select: { body: true } })).map((item) => item.body).join(" "); assert.equal(bodies.includes("Conteudo confidencial"), false); assert.equal(bodies.includes("Contato privado"), false); assert.equal(bodies.includes(`${tag}-candidate-a@test.local`), false); });
  test("46 dashboard permission filtering", async () => { const stored = await prisma.hubMember.findMany({ where: { id: { in: [finance, member] } }, select: { id: true, role: true } }); const financeRole = stored.find((item) => item.id === finance)!.role; const memberRole = stored.find((item) => item.id === member)!.role; assert.equal(hasHubPermission(financeRole, "finance:review"), true); assert.equal(hasHubPermission(memberRole, "finance:review"), false); assert.equal(hasHubPermission(financeRole, "people:read-sensitive"), false); });
  test("47 no integration-test skips", async () => { const result = await prisma.$queryRaw<Array<{ version: string }>>`SELECT version()`; assert.match(result[0].version, /PostgreSQL/); assert.ok(process.env.ATLAS_HUB_TEST_DATABASE_URL); });
}
