import assert from "node:assert/strict";
import test, { after, before } from "node:test";
import { PrismaClient } from "@prisma/client";
import type { HubOrganizationContext } from "./auth";
import { handleApproveFinancialEntry, handleAssignOnboarding, handleCreateFinancialEntry, handleCreateReimbursement, handleMoveCandidateStage, handleRecordSettlement, handleReverseSettlement, handleReviewReimbursement, handleSubmitEvaluation, handleSubmitFinancialEntry, handleSubmitReimbursement, handleUpdateDevelopmentGoal, handleUpdateManagedProfile, handleUpdateOwnProfile } from "./operations-handlers";
import { setFinancialPeriodStatus } from "./operations-service";

const databaseUrl = process.env.ATLAS_HUB_TEST_DATABASE_URL;
if (!databaseUrl) throw new Error("ATLAS_HUB_TEST_DATABASE_URL e obrigatoria para os testes operacionais.");
else {
  const prisma = new PrismaClient({ datasourceUrl: databaseUrl }); const tag = `ops-${Date.now()}-${Math.random().toString(36).slice(2)}`;
  let orgA = "", orgB = "", adminId = "", financeId = "", memberId = "", categoryId = "", installmentId = "", entryId = "";
  function session(id: string, role: "ADMIN" | "FINANCE" | "MEMBER", organizationId = orgA): HubOrganizationContext { return { memberId: id, organizationId, role, directorateId: null, sessionVersion: 1, email: `${id}@test.local`, permissions: [], organization: { id: organizationId, name: tag, hubName: tag, slug: tag, logoUrl: null, timezone: "America/Fortaleza", locale: "pt-BR", currency: "BRL", isActive: true } } as unknown as HubOrganizationContext; }
  before(async () => {
    const a = await prisma.hubOrganization.create({ data: { name: `${tag}-a`, hubName: tag, slug: `${tag}-a` } }); const b = await prisma.hubOrganization.create({ data: { name: `${tag}-b`, hubName: tag, slug: `${tag}-b` } }); orgA = a.id; orgB = b.id;
    const [admin, finance, member] = await Promise.all([
      prisma.hubMember.create({ data: { organizationId: orgA, email: `${tag}-admin@test.local`, normalizedEmail: `${tag}-admin@test.local`, name: "Admin", passwordHash: "test", role: "ADMIN", status: "ACTIVE", mustChangePassword: false } }),
      prisma.hubMember.create({ data: { organizationId: orgA, email: `${tag}-finance@test.local`, normalizedEmail: `${tag}-finance@test.local`, name: "Finance", passwordHash: "test", role: "FINANCE", status: "ACTIVE", mustChangePassword: false } }),
      prisma.hubMember.create({ data: { organizationId: orgA, email: `${tag}-member@test.local`, normalizedEmail: `${tag}-member@test.local`, name: "Member", passwordHash: "test", role: "MEMBER", status: "ACTIVE", mustChangePassword: false } }),
    ]); adminId = admin.id; financeId = finance.id; memberId = member.id;
    categoryId = (await prisma.hubFinancialCategory.create({ data: { organizationId: orgA, name: "Servicos", normalizedName: `${tag}-servicos`, type: "BOTH" } })).id;
  });
  after(async () => { await prisma.$transaction(async (tx) => {
    const scoped = { organizationId: { in: [orgA, orgB] } };
    await tx.hubEvaluationResponse.deleteMany({ where: scoped }); await tx.hubEvaluation.deleteMany({ where: scoped }); await tx.hubEvaluationCriterion.deleteMany({ where: scoped }); await tx.hubPeopleCycle.deleteMany({ where: scoped });
    await tx.hubCandidateStageEvent.deleteMany({ where: scoped }); await tx.hubCandidate.deleteMany({ where: scoped }); await tx.hubRecruitmentStage.deleteMany({ where: scoped }); await tx.hubRecruitmentProcess.deleteMany({ where: scoped });
    await tx.hubOnboardingAssignmentItem.deleteMany({ where: scoped }); await tx.hubOnboardingAssignment.deleteMany({ where: scoped }); await tx.hubOnboardingTemplateItem.deleteMany({ where: scoped }); await tx.hubOnboardingTemplate.deleteMany({ where: scoped });
    await tx.hubDevelopmentGoal.deleteMany({ where: scoped }); await tx.hubDevelopmentPlan.deleteMany({ where: scoped }); await tx.hubMemberProfile.deleteMany({ where: scoped });
    await tx.hubReimbursementItem.deleteMany({ where: scoped }); await tx.hubReimbursementRequest.deleteMany({ where: scoped });
    await tx.hubFinancialSettlement.deleteMany({ where: scoped }); await tx.hubFinancialInstallment.deleteMany({ where: scoped }); await tx.hubFinancialEntry.deleteMany({ where: scoped }); await tx.hubFinancialPeriod.deleteMany({ where: scoped }); await tx.hubFinancialCategory.deleteMany({ where: scoped });
    await tx.hubNotification.deleteMany({ where: scoped }); await tx.hubAuditLog.deleteMany({ where: scoped }); await tx.hubMember.deleteMany({ where: scoped }); await tx.hubOrganization.deleteMany({ where: { id: { in: [orgA, orgB] } } });
  }); await prisma.$disconnect(); });

  test("actual handler creates entry and installments transactionally", async () => { const entry = await handleCreateFinancialEntry(prisma, session(adminId, "ADMIN"), { direction: "PAYABLE", description: "Fornecedor", categoryId, issueDate: "2026-07-14", competenceDate: "2026-07-14", totalCents: 10000, installments: [{ amountCents: 6000, dueDate: "2026-07-20" }, { amountCents: 4000, dueDate: "2026-08-20" }], idempotencyKey: `${tag}-entry` }); entryId = entry.id; const installments = await prisma.hubFinancialInstallment.findMany({ where: { entryId }, orderBy: { number: "asc" } }); assert.deepEqual(installments.map((item) => item.amountCents), [6000, 4000]); installmentId = installments[0].id; });
  test("entry retry returns existing resource", async () => { const entry = await handleCreateFinancialEntry(prisma, session(adminId, "ADMIN"), { direction: "PAYABLE", description: "Fornecedor", categoryId, issueDate: "2026-07-14", competenceDate: "2026-07-14", totalCents: 10000, installments: [{ amountCents: 6000, dueDate: "2026-07-20" }, { amountCents: 4000, dueDate: "2026-08-20" }], idempotencyKey: `${tag}-entry` }); assert.equal(entry.id, entryId); });
  test("idempotency key reuse with different payload returns 409", async () => { await assert.rejects(() => handleCreateFinancialEntry(prisma, session(adminId, "ADMIN"), { direction: "PAYABLE", description: "Outro", categoryId, issueDate: "2026-07-14", competenceDate: "2026-07-14", totalCents: 10000, installments: [{ amountCents: 10000, dueDate: "2026-07-20" }], idempotencyKey: `${tag}-entry` }), (error: unknown) => (error as { status?: number }).status === 409); });
  test("cross-organization category uses generic not-found", async () => { const foreign = await prisma.hubFinancialCategory.create({ data: { organizationId: orgB, name: "Foreign", normalizedName: tag, type: "BOTH" } }); await assert.rejects(() => handleCreateFinancialEntry(prisma, session(adminId, "ADMIN"), { direction: "PAYABLE", description: "Cross", categoryId: foreign.id, issueDate: "2026-07-14", competenceDate: "2026-07-14", totalCents: 1, installments: [{ amountCents: 1, dueDate: "2026-07-20" }], idempotencyKey: `${tag}-cross` }), (error: unknown) => (error as { status?: number }).status === 404); });
  test("submit and independent approval use actual handlers", async () => { await handleSubmitFinancialEntry(prisma, session(adminId, "ADMIN"), entryId); const approved = await handleApproveFinancialEntry(prisma, session(financeId, "FINANCE"), entryId); assert.equal(approved.status, "APPROVED"); });
  test("partial settlement and excessive settlement protection", async () => { await handleRecordSettlement(prisma, session(financeId, "FINANCE"), entryId, { installmentId, amountCents: 2500, settledAt: "2026-07-15T12:00:00Z", method: "PIX", idempotencyKey: `${tag}-settle-1` }); assert.equal((await prisma.hubFinancialEntry.findUniqueOrThrow({ where: { id: entryId } })).status, "PARTIALLY_SETTLED"); await assert.rejects(() => handleRecordSettlement(prisma, session(financeId, "FINANCE"), entryId, { installmentId, amountCents: 4000, settledAt: "2026-07-15T12:00:00Z", method: "PIX", idempotencyKey: `${tag}-settle-too-much` }), (error: unknown) => (error as { status?: number }).status === 409); });
  test("settlement reversal preserves original record", async () => { const settlement = await prisma.hubFinancialSettlement.findFirstOrThrow({ where: { organizationId: orgA, idempotencyKey: `${tag}-settle-1` } }); const reversed = await handleReverseSettlement(prisma, session(financeId, "FINANCE"), settlement.id, { reason: "Pagamento estornado" }); assert.ok(reversed.reversedAt); assert.equal(await prisma.hubFinancialSettlement.count({ where: { id: settlement.id } }), 1); });
  test("closed period blocks settlement mutations", async () => { await setFinancialPeriodStatus(prisma, { id: financeId, organizationId: orgA, role: "FINANCE", directorateId: null }, { year: 2026, month: 7, status: "CLOSED" }); await assert.rejects(() => handleRecordSettlement(prisma, session(financeId, "FINANCE"), entryId, { installmentId, amountCents: 100, settledAt: "2026-07-16T12:00:00Z", method: "PIX", idempotencyKey: `${tag}-closed` }), (error: unknown) => (error as { status?: number }).status === 409); await setFinancialPeriodStatus(prisma, { id: financeId, organizationId: orgA, role: "FINANCE", directorateId: null }, { year: 2026, month: 7, status: "OPEN", reason: "Correcao autorizada" }); });
  test("own profile handler excludes administrator-only fields", async () => { const profile = await handleUpdateOwnProfile(prisma, session(memberId, "MEMBER"), { phone: "85999990000", university: "UF", linkedinUrl: "https://linkedin.com/in/test", bio: "Bio", emergencyContactName: "Must be ignored" }); assert.equal(profile.memberId, memberId); assert.equal(profile.emergencyContactName, null); });
  test("actual sensitive-profile handler rejects unauthorized fields", async () => { await assert.rejects(() => handleUpdateManagedProfile(prisma, session(memberId, "MEMBER"), memberId, { emergencyContactName: "Nao autorizado" }), (error: unknown) => (error as { status?: number }).status === 403); });
  test("reimbursement actual handlers create exactly one payable entry", async () => { const request = await handleCreateReimbursement(prisma, session(memberId, "MEMBER"), { description: "Transporte", items: [{ description: "Taxi", expenseDate: "2026-07-10", amountCents: 3500, categoryId, receiptReference: "https://example.com/receipt" }], idempotencyKey: `${tag}-reimbursement` }); await handleSubmitReimbursement(prisma, session(memberId, "MEMBER"), request.id); const approved = await handleReviewReimbursement(prisma, session(financeId, "FINANCE"), request.id, { decision: "APPROVE" }); assert.equal(approved.status, "APPROVED"); assert.ok(approved.financialEntryId); assert.equal(await prisma.hubFinancialEntry.count({ where: { organizationId: orgA, idempotencyKey: `reimbursement:${request.id}` } }), 1); });
  test("reimbursement requester cannot self-review", async () => { const request = await handleCreateReimbursement(prisma, session(memberId, "MEMBER"), { description: "Alimentacao", items: [{ description: "Almoco", expenseDate: "2026-07-10", amountCents: 1000, categoryId }], idempotencyKey: `${tag}-reimbursement-self` }); await handleSubmitReimbursement(prisma, session(memberId, "MEMBER"), request.id); await assert.rejects(() => handleReviewReimbursement(prisma, session(memberId, "MEMBER"), request.id, { decision: "APPROVE" }), (error: unknown) => (error as { status?: number }).status === 403); });
  test("onboarding assignment uses actual handler and transactional items", async () => { const template = await prisma.hubOnboardingTemplate.create({ data: { organizationId: orgA, name: "Entrada", createdById: adminId } }); await prisma.hubOnboardingTemplateItem.create({ data: { organizationId: orgA, templateId: template.id, title: "Ler guia", order: 1, dueAfterDays: 2 } }); const assignment = await handleAssignOnboarding(prisma, session(adminId, "ADMIN"), { templateId: template.id, memberId }); assert.equal(await prisma.hubOnboardingAssignmentItem.count({ where: { assignmentId: assignment.id } }), 1); });
  test("development goal uses optimistic concurrency", async () => { const plan = await prisma.hubDevelopmentPlan.create({ data: { organizationId: orgA, memberId, title: "PDI", createdById: adminId } }); const goal = await prisma.hubDevelopmentGoal.create({ data: { organizationId: orgA, planId: plan.id, ownerMemberId: memberId, title: "Meta", status: "ACTIVE" } }); const updated = await handleUpdateDevelopmentGoal(prisma, session(memberId, "MEMBER"), goal.id, { version: 1, progress: 50 }); assert.equal(updated.version, 2); await assert.rejects(() => handleUpdateDevelopmentGoal(prisma, session(memberId, "MEMBER"), goal.id, { version: 1, progress: 60 }), (error: unknown) => (error as { status?: number }).status === 409); });
  test("evaluation handler submits once and keeps comments out of audit metadata", async () => { const cycle = await prisma.hubPeopleCycle.create({ data: { organizationId: orgA, name: "Cycle", status: "ACTIVE", createdById: adminId } }); const criterion = await prisma.hubEvaluationCriterion.create({ data: { organizationId: orgA, cycleId: cycle.id, title: "Entrega", order: 1 } }); const evaluation = await prisma.hubEvaluation.create({ data: { organizationId: orgA, cycleId: cycle.id, evaluatorMemberId: memberId, evaluatedMemberId: memberId, type: "SELF" } }); const submitted = await handleSubmitEvaluation(prisma, session(memberId, "MEMBER"), evaluation.id, { version: 1, responses: [{ criterionId: criterion.id, score: 5, comment: "Sensitive body" }] }); assert.equal(submitted.status, "SUBMITTED"); const audit = await prisma.hubAuditLog.findFirstOrThrow({ where: { entityId: evaluation.id, action: "EVALUATION_COMPLETED" } }); assert.equal(JSON.stringify(audit.metadata || {}).includes("Sensitive body"), false); await assert.rejects(() => handleSubmitEvaluation(prisma, session(memberId, "MEMBER"), evaluation.id, { version: 2, responses: [{ criterionId: criterion.id, score: 5 }] }), (error: unknown) => (error as { status?: number }).status === 409); });
  test("candidate stage movement is append-only and idempotent", async () => { const process = await prisma.hubRecruitmentProcess.create({ data: { organizationId: orgA, title: "Trainee", status: "OPEN", createdById: adminId } }); const stage = await prisma.hubRecruitmentStage.create({ data: { organizationId: orgA, processId: process.id, name: "Entrevista", order: 1 } }); const candidate = await prisma.hubCandidate.create({ data: { organizationId: orgA, processId: process.id, name: "Candidate", email: `${tag}@candidate.local`, normalizedEmail: `${tag}@candidate.local` } }); const moved = await handleMoveCandidateStage(prisma, session(adminId, "ADMIN"), candidate.id, { toStageId: stage.id, expectedVersion: 1, idempotencyKey: `${tag}-move` }); const retry = await handleMoveCandidateStage(prisma, session(adminId, "ADMIN"), candidate.id, { toStageId: stage.id, expectedVersion: 1, idempotencyKey: `${tag}-move` }); assert.equal(retry.id, moved.id); assert.equal(await prisma.hubCandidateStageEvent.count({ where: { candidateId: candidate.id } }), 1); });
}
