import type { PrismaClient } from "@prisma/client";
import type { HubOrganizationContext } from "./auth";
import { HubApiError } from "./api";
import { approveFinancialEntry, assignEvaluation, assignOnboarding, assessCompetency, cancelFinancialEntry, cancelReimbursement, completeOnboardingItem, createBudget, createCandidate, createCompetency, createDevelopmentGoal, createFeedback, createFinancialEntry, createOnboardingTemplate, createParticipationRecord, createPeopleCycle, createRecognition, createRecruitmentProcess, createReimbursement, evaluateCandidate, hireCandidate, moveCandidateStage, recordSettlement, rejectCandidate, rejectFinancialEntry, reverseSettlement, reviewReimbursement, setBudgetStatus, setCandidateStatus, setPeopleCycleStatus, setRecruitmentProcessStatus, submitEvaluation, submitFinancialEntry, submitReimbursement, updateDevelopmentGoal, updateDraftFinancialEntry, updateDraftReimbursement, updateManagedProfile, updateOnboardingTemplate, updateOwnProfile } from "./operations-service";

type Body = Record<string, unknown>;
function body(value: unknown): Body { if (!value || typeof value !== "object" || Array.isArray(value)) throw new HubApiError("Corpo da requisicao invalido.", 400); return value as Body; }
function text(value: unknown, field: string) { if (typeof value !== "string" || !value.trim()) throw new HubApiError(`${field} e obrigatorio.`, 400); return value.trim(); }
function integer(value: unknown, field: string) { if (!Number.isInteger(value)) throw new HubApiError(`${field} invalido.`, 400); return value as number; }
function date(value: unknown, field: string) { const result = new Date(text(value, field)); if (Number.isNaN(result.valueOf())) throw new HubApiError(`${field} invalida.`, 400); return result; }
function oneOf<T extends string>(value: unknown, field: string, values: readonly T[]): T { const parsed = text(value, field); if (!values.includes(parsed as T)) throw new HubApiError(`${field} invalido.`, 400); return parsed as T; }
function actor(session: HubOrganizationContext) { return { id: session.memberId, organizationId: session.organizationId, role: session.role, directorateId: session.directorateId ?? null }; }

export async function handleCreateFinancialEntry(prisma: PrismaClient, session: HubOrganizationContext, value: unknown) {
  const input = body(value); const installments = Array.isArray(input.installments) ? input.installments.map((item) => { const parsed = body(item); return { amountCents: integer(parsed.amountCents, "amountCents"), dueDate: date(parsed.dueDate, "dueDate") }; }) : [];
  return createFinancialEntry(prisma, actor(session), { direction: oneOf(input.direction, "direction", ["PAYABLE", "RECEIVABLE"] as const), description: text(input.description, "description"), categoryId: text(input.categoryId, "categoryId"), costCenterId: typeof input.costCenterId === "string" ? input.costCenterId : null, counterpartyId: typeof input.counterpartyId === "string" ? input.counterpartyId : null, projectId: typeof input.projectId === "string" ? input.projectId : null, issueDate: date(input.issueDate, "issueDate"), competenceDate: date(input.competenceDate, "competenceDate"), totalCents: integer(input.totalCents, "totalCents"), installments, idempotencyKey: text(input.idempotencyKey, "idempotencyKey") });
}
export async function handleUpdateDraftFinancialEntry(prisma: PrismaClient, session: HubOrganizationContext, id: string, value: unknown) { const input = body(value); const installments = Array.isArray(input.installments) ? input.installments.map((item) => { const parsed = body(item); return { amountCents: integer(parsed.amountCents, "amountCents"), dueDate: date(parsed.dueDate, "dueDate") }; }) : []; return updateDraftFinancialEntry(prisma, actor(session), id, { direction: oneOf(input.direction, "direction", ["PAYABLE", "RECEIVABLE"] as const), description: text(input.description, "description"), categoryId: text(input.categoryId, "categoryId"), costCenterId: typeof input.costCenterId === "string" ? input.costCenterId : null, counterpartyId: typeof input.counterpartyId === "string" ? input.counterpartyId : null, projectId: typeof input.projectId === "string" ? input.projectId : null, issueDate: date(input.issueDate, "issueDate"), competenceDate: date(input.competenceDate, "competenceDate"), totalCents: integer(input.totalCents, "totalCents"), installments }); }
export const handleSubmitFinancialEntry = (prisma: PrismaClient, session: HubOrganizationContext, id: string) => submitFinancialEntry(prisma, actor(session), id);
export const handleApproveFinancialEntry = (prisma: PrismaClient, session: HubOrganizationContext, id: string) => approveFinancialEntry(prisma, actor(session), id);
export function handleRejectFinancialEntry(prisma: PrismaClient, session: HubOrganizationContext, id: string, value: unknown) { const input = body(value); return rejectFinancialEntry(prisma, actor(session), id, text(input.reason, "reason")); }
export function handleCancelFinancialEntry(prisma: PrismaClient, session: HubOrganizationContext, id: string, value: unknown) { const input = body(value); return cancelFinancialEntry(prisma, actor(session), id, text(input.reason, "reason")); }
export function handleRecordSettlement(prisma: PrismaClient, session: HubOrganizationContext, id: string, value: unknown) { const input = body(value); return recordSettlement(prisma, actor(session), id, { installmentId: text(input.installmentId, "installmentId"), amountCents: integer(input.amountCents, "amountCents"), settledAt: date(input.settledAt, "settledAt"), method: oneOf(input.method, "method", ["PIX", "BANK_TRANSFER", "CASH", "CARD", "BOLETO", "OTHER"] as const), reference: typeof input.reference === "string" ? input.reference : null, idempotencyKey: text(input.idempotencyKey, "idempotencyKey") }); }
export function handleReverseSettlement(prisma: PrismaClient, session: HubOrganizationContext, id: string, value: unknown) { const input = body(value); return reverseSettlement(prisma, actor(session), id, text(input.reason, "reason")); }
export function handleUpdateOwnProfile(prisma: PrismaClient, session: HubOrganizationContext, value: unknown) { const input = body(value); return updateOwnProfile(prisma, actor(session), { phone: typeof input.phone === "string" ? input.phone : null, university: typeof input.university === "string" ? input.university : null, course: typeof input.course === "string" ? input.course : null, semester: typeof input.semester === "string" ? input.semester : null, linkedinUrl: typeof input.linkedinUrl === "string" ? input.linkedinUrl : null, bio: typeof input.bio === "string" ? input.bio : null }); }
export function handleUpdateDevelopmentGoal(prisma: PrismaClient, session: HubOrganizationContext, id: string, value: unknown) { const input = body(value); return updateDevelopmentGoal(prisma, actor(session), id, { version: integer(input.version, "version"), progress: integer(input.progress, "progress"), status: typeof input.status === "string" ? input.status as never : undefined }); }
export function handleSubmitEvaluation(prisma: PrismaClient, session: HubOrganizationContext, id: string, value: unknown) { const input = body(value); const responses = Array.isArray(input.responses) ? input.responses.map((item) => { const parsed = body(item); return { criterionId: text(parsed.criterionId, "criterionId"), score: integer(parsed.score, "score"), comment: typeof parsed.comment === "string" ? parsed.comment : undefined }; }) : []; return submitEvaluation(prisma, actor(session), id, { version: integer(input.version, "version"), responses }); }
export function handleMoveCandidateStage(prisma: PrismaClient, session: HubOrganizationContext, id: string, value: unknown) { const input = body(value); return moveCandidateStage(prisma, actor(session), id, { toStageId: text(input.toStageId, "toStageId"), expectedVersion: integer(input.expectedVersion, "expectedVersion"), idempotencyKey: text(input.idempotencyKey, "idempotencyKey"), reason: typeof input.reason === "string" ? input.reason : undefined }); }
export function handleCreateReimbursement(prisma: PrismaClient, session: HubOrganizationContext, value: unknown) { const input = body(value); const items = Array.isArray(input.items) ? input.items.map((item) => { const parsed = body(item); return { description: text(parsed.description, "description"), expenseDate: date(parsed.expenseDate, "expenseDate"), amountCents: integer(parsed.amountCents, "amountCents"), categoryId: text(parsed.categoryId, "categoryId"), receiptReference: typeof parsed.receiptReference === "string" ? parsed.receiptReference : null }; }) : []; return createReimbursement(prisma, actor(session), { description: text(input.description, "description"), costCenterId: typeof input.costCenterId === "string" ? input.costCenterId : null, items, idempotencyKey: text(input.idempotencyKey, "idempotencyKey") }); }
export const handleSubmitReimbursement = (prisma: PrismaClient, session: HubOrganizationContext, id: string) => submitReimbursement(prisma, actor(session), id);
export function handleReviewReimbursement(prisma: PrismaClient, session: HubOrganizationContext, id: string, value: unknown) { const input = body(value); return reviewReimbursement(prisma, actor(session), id, { decision: oneOf(input.decision, "decision", ["APPROVE", "REJECT"] as const), rejectionReason: typeof input.rejectionReason === "string" ? input.rejectionReason : undefined }); }
export function handleUpdateDraftReimbursement(prisma: PrismaClient, session: HubOrganizationContext, id: string, value: unknown) { const input = body(value); const items = Array.isArray(input.items) ? input.items.map((item) => { const parsed = body(item); return { description: text(parsed.description, "description"), expenseDate: date(parsed.expenseDate, "expenseDate"), amountCents: integer(parsed.amountCents, "amountCents"), categoryId: text(parsed.categoryId, "categoryId"), receiptReference: typeof parsed.receiptReference === "string" ? parsed.receiptReference : null }; }) : []; return updateDraftReimbursement(prisma, actor(session), id, { description: text(input.description, "description"), costCenterId: typeof input.costCenterId === "string" ? input.costCenterId : null, items }); }
export const handleCancelReimbursement = (prisma: PrismaClient, session: HubOrganizationContext, id: string) => cancelReimbursement(prisma, actor(session), id);
export function handleAssignOnboarding(prisma: PrismaClient, session: HubOrganizationContext, value: unknown) { const input = body(value); return assignOnboarding(prisma, actor(session), { templateId: text(input.templateId, "templateId"), memberId: text(input.memberId, "memberId") }); }
export function handleCreateOnboardingTemplate(prisma: PrismaClient, session: HubOrganizationContext, value: unknown) { const input = body(value); const items = Array.isArray(input.items) ? input.items.map((item) => { const parsed = body(item); return { title: text(parsed.title, "title"), description: typeof parsed.description === "string" ? parsed.description : null, dueAfterDays: typeof parsed.dueAfterDays === "number" ? integer(parsed.dueAfterDays, "dueAfterDays") : null }; }) : []; return createOnboardingTemplate(prisma, actor(session), { name: text(input.name, "name"), directorateId: typeof input.directorateId === "string" ? input.directorateId : null, items }); }
export function handleUpdateOnboardingTemplate(prisma: PrismaClient, session: HubOrganizationContext, id: string, value: unknown) { const input = body(value); return updateOnboardingTemplate(prisma, actor(session), id, { name: typeof input.name === "string" ? input.name : undefined, isActive: typeof input.isActive === "boolean" ? input.isActive : undefined }); }
export function handleCreateBudget(prisma: PrismaClient, session: HubOrganizationContext, value: unknown) { const input = body(value); const lines = Array.isArray(input.lines) ? input.lines.map((item) => { const parsed = body(item); return { categoryId: text(parsed.categoryId, "categoryId"), costCenterId: typeof parsed.costCenterId === "string" ? parsed.costCenterId : null, month: integer(parsed.month, "month"), plannedCents: integer(parsed.plannedCents, "plannedCents") }; }) : []; return createBudget(prisma, actor(session), { name: text(input.name, "name"), year: integer(input.year, "year"), lines }); }
export function handleSetBudgetStatus(prisma: PrismaClient, session: HubOrganizationContext, id: string, value: unknown) { const input = body(value); return setBudgetStatus(prisma, actor(session), id, text(input.status, "status") as "APPROVED" | "ARCHIVED"); }
export function handleUpdateManagedProfile(prisma: PrismaClient, session: HubOrganizationContext, id: string, value: unknown) { const input = body(value); return updateManagedProfile(prisma, actor(session), id, { joinedAt: input.joinedAt ? date(input.joinedAt, "joinedAt") : null, leftAt: input.leftAt ? date(input.leftAt, "leftAt") : null, employmentType: typeof input.employmentType === "string" ? input.employmentType : null, emergencyContactName: typeof input.emergencyContactName === "string" ? input.emergencyContactName : null, emergencyContactPhone: typeof input.emergencyContactPhone === "string" ? input.emergencyContactPhone : null, birthDate: input.birthDate ? date(input.birthDate, "birthDate") : null, visibility: typeof input.visibility === "string" ? input.visibility as "PRIVATE" | "ORGANIZATION" : undefined }); }
export function handleCompleteOnboardingItem(prisma: PrismaClient, session: HubOrganizationContext, id: string, value: unknown) { const input = body(value); return completeOnboardingItem(prisma, actor(session), id, integer(input.version, "version")); }
export function handleCreateCompetency(prisma: PrismaClient, session: HubOrganizationContext, value: unknown) { const input = body(value); return createCompetency(prisma, actor(session), { name: text(input.name, "name"), description: typeof input.description === "string" ? input.description : null, category: typeof input.category === "string" ? input.category : null }); }
export function handleAssessCompetency(prisma: PrismaClient, session: HubOrganizationContext, value: unknown) { const input = body(value); return assessCompetency(prisma, actor(session), { memberId: text(input.memberId, "memberId"), competencyId: text(input.competencyId, "competencyId"), level: integer(input.level, "level") }); }
export function handleCreateDevelopmentGoal(prisma: PrismaClient, session: HubOrganizationContext, value: unknown) { const input = body(value); return createDevelopmentGoal(prisma, actor(session), { ownerMemberId: text(input.ownerMemberId, "ownerMemberId"), title: text(input.title, "title"), description: typeof input.description === "string" ? input.description : null, managerMemberId: typeof input.managerMemberId === "string" ? input.managerMemberId : null, dueDate: input.dueDate ? date(input.dueDate, "dueDate") : null }); }
export function handleCreatePeopleCycle(prisma: PrismaClient, session: HubOrganizationContext, value: unknown) { const input = body(value); const criteria = Array.isArray(input.criteria) ? input.criteria.map((item) => { const parsed = body(item); return { title: text(parsed.title, "title"), description: typeof parsed.description === "string" ? parsed.description : null, scaleMin: typeof parsed.scaleMin === "number" ? integer(parsed.scaleMin, "scaleMin") : undefined, scaleMax: typeof parsed.scaleMax === "number" ? integer(parsed.scaleMax, "scaleMax") : undefined }; }) : []; return createPeopleCycle(prisma, actor(session), { name: text(input.name, "name"), startsAt: input.startsAt ? date(input.startsAt, "startsAt") : null, endsAt: input.endsAt ? date(input.endsAt, "endsAt") : null, criteria }); }
export function handleSetPeopleCycleStatus(prisma: PrismaClient, session: HubOrganizationContext, id: string, value: unknown) { const input = body(value); return setPeopleCycleStatus(prisma, actor(session), id, text(input.status, "status") as "ACTIVE" | "CLOSED" | "ARCHIVED"); }
export function handleCreateFeedback(prisma: PrismaClient, session: HubOrganizationContext, value: unknown) { const input = body(value); return createFeedback(prisma, actor(session), { recipientMemberId: text(input.recipientMemberId, "recipientMemberId"), body: text(input.body, "body"), visibility: text(input.visibility, "visibility") as "PRIVATE_TO_RECIPIENT" | "MANAGER_AND_RECIPIENT" | "PEOPLE_ADMIN", cycleId: typeof input.cycleId === "string" ? input.cycleId : null }); }
export function handleAssignEvaluation(prisma: PrismaClient, session: HubOrganizationContext, value: unknown) { const input = body(value); return assignEvaluation(prisma, actor(session), { cycleId: text(input.cycleId, "cycleId"), evaluatorMemberId: text(input.evaluatorMemberId, "evaluatorMemberId"), evaluatedMemberId: text(input.evaluatedMemberId, "evaluatedMemberId"), type: text(input.type, "type") as "SELF" | "MANAGER" | "PEER" }); }
export function handleCreateRecognition(prisma: PrismaClient, session: HubOrganizationContext, value: unknown) { const input = body(value); return createRecognition(prisma, actor(session), { recipientMemberId: text(input.recipientMemberId, "recipientMemberId"), title: text(input.title, "title"), description: text(input.description, "description"), visibility: text(input.visibility, "visibility") as "PRIVATE" | "ORGANIZATION" }); }
export function handleCreateParticipationRecord(prisma: PrismaClient, session: HubOrganizationContext, value: unknown) { const input = body(value); return createParticipationRecord(prisma, actor(session), { memberId: text(input.memberId, "memberId"), date: date(input.date, "date"), type: text(input.type, "type"), source: text(input.source, "source") }); }
export function handleCreateRecruitmentProcess(prisma: PrismaClient, session: HubOrganizationContext, value: unknown) { const input = body(value); return createRecruitmentProcess(prisma, actor(session), { title: text(input.title, "title"), description: typeof input.description === "string" ? input.description : null, stages: Array.isArray(input.stages) ? input.stages.map((stage) => text(stage, "stage")) : [] }); }
export function handleSetRecruitmentProcessStatus(prisma: PrismaClient, session: HubOrganizationContext, id: string, value: unknown) { const input = body(value); return setRecruitmentProcessStatus(prisma, actor(session), id, text(input.status, "status") as "OPEN" | "CLOSED" | "ARCHIVED"); }
export function handleCreateCandidate(prisma: PrismaClient, session: HubOrganizationContext, value: unknown) { const input = body(value); return createCandidate(prisma, actor(session), { processId: text(input.processId, "processId"), name: text(input.name, "name"), email: text(input.email, "email"), phone: typeof input.phone === "string" ? input.phone : null, notes: typeof input.notes === "string" ? input.notes : null }); }
export function handleEvaluateCandidate(prisma: PrismaClient, session: HubOrganizationContext, id: string, value: unknown) { const input = body(value); return evaluateCandidate(prisma, actor(session), id, { score: integer(input.score, "score"), comments: typeof input.comments === "string" ? input.comments : null }); }
export function handleRejectCandidate(prisma: PrismaClient, session: HubOrganizationContext, id: string, value: unknown) { const input = body(value); return rejectCandidate(prisma, actor(session), id, { expectedVersion: integer(input.expectedVersion, "expectedVersion"), reason: text(input.reason, "reason") }); }
export function handleSetCandidateStatus(prisma: PrismaClient, session: HubOrganizationContext, id: string, value: unknown) { const input = body(value); return setCandidateStatus(prisma, actor(session), id, { expectedVersion: integer(input.expectedVersion, "expectedVersion"), status: text(input.status, "status") as "ACTIVE" | "APPROVED" | "WITHDRAWN" }); }
export function handleHireCandidate(prisma: PrismaClient, session: HubOrganizationContext, id: string, value: unknown) { const input = body(value); return hireCandidate(prisma, actor(session), id, { expectedVersion: integer(input.expectedVersion, "expectedVersion"), confirm: input.confirm === true, role: typeof input.role === "string" ? input.role as "MEMBER" | "VIEWER" : undefined, directorateId: typeof input.directorateId === "string" ? input.directorateId : null }); }
