import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import path from "node:path";
import test from "node:test";
import { PrismaClient } from "@prisma/client";
import { HubApiError } from "./api";
import { hashHubPassword } from "./auth";
import { resolveHubDashboardScope } from "./dashboard-context";
import { hashHubInvitationToken, HUB_INVITATION_TOKEN_BYTES } from "./invitation-token";
import { canAccessHubSettings } from "./settings-policy";
import { acceptHubInvitation, createHubInvitation, getHubSettings, previewHubInvitation, regenerateLegacyHubInvitation, revokeHubInvitation, transferHubPresidency, updateHubDirectorateLeadership, updateHubMemberClassification } from "./settings-service";

const databaseUrl = process.env.ATLAS_HUB_TEST_DATABASE_URL || process.env.ECONOMIK_TEST_DATABASE_URL;
if (!databaseUrl) throw new Error("ATLAS_HUB_TEST_DATABASE_URL é obrigatória para os testes de ajustes do Hub.");
const prisma = new PrismaClient({ datasourceUrl: databaseUrl });
const suffix = `${Date.now()}-${Math.random().toString(36).slice(2)}`;
const password = "SenhaForte123";
function tokenFrom(result: { invitationUrl?: string }) { const token = result.invitationUrl?.split("/").pop(); assert.ok(token); return token; }
function apiStatus(status: number) { return (error: unknown) => error instanceof HubApiError && error.status === status; }

test("política de ajustes separa papel técnico e posição organizacional", () => {
  assert.equal(canAccessHubSettings("SUPER_ADMIN", "MEMBER"), true); assert.equal(canAccessHubSettings("MEMBER", "PRESIDENT"), true); assert.equal(canAccessHubSettings("VIEWER", "COUNSELOR"), true); assert.equal(canAccessHubSettings("DIRECTOR", "MEMBER"), false);
});

test("convites seguros e governança do Hub funcionam em PostgreSQL", async (suite) => {
  const org = await prisma.hubOrganization.create({ data: { name: `Settings ${suffix}`, hubName: "Settings", slug: `settings-${suffix}` } });
  const foreignOrg = await prisma.hubOrganization.create({ data: { name: `Foreign ${suffix}`, hubName: "Foreign", slug: `foreign-settings-${suffix}` } });
  const dir = await prisma.hubDirectorate.create({ data: { organizationId: org.id, name: "Projetos", slug: `projects-${suffix}` } });
  const otherDir = await prisma.hubDirectorate.create({ data: { organizationId: org.id, name: "Comercial", slug: `commercial-${suffix}` } });
  const foreignDir = await prisma.hubDirectorate.create({ data: { organizationId: foreignOrg.id, name: "Foreign", slug: `foreign-${suffix}` } });
  const actorAccount = await prisma.hubAccount.create({ data: { email: `president-${suffix}@test.local`, normalizedEmail: `president-${suffix}@test.local`, passwordHash: "test" } });
  const actor = await prisma.hubMember.create({ data: { organizationId: org.id, accountId: actorAccount.id, name: "President", email: actorAccount.email, normalizedEmail: actorAccount.normalizedEmail, passwordHash: "test", role: "MEMBER", organizationPosition: "PRESIDENT", status: "ACTIVE" } });
  const member = await prisma.hubMember.create({ data: { organizationId: org.id, name: "Member", email: `member-${suffix}@test.local`, normalizedEmail: `member-${suffix}@test.local`, passwordHash: "test", status: "ACTIVE", directorateId: dir.id } });
  const counselor = await prisma.hubMember.create({ data: { organizationId: org.id, name: "Counselor", email: `counselor-${suffix}@test.local`, normalizedEmail: `counselor-${suffix}@test.local`, passwordHash: "test", status: "ACTIVE", organizationPosition: "COUNSELOR" } });
  const foreign = await prisma.hubMember.create({ data: { organizationId: foreignOrg.id, name: "Foreign", email: `foreign-${suffix}@test.local`, normalizedEmail: `foreign-${suffix}@test.local`, passwordHash: "test", status: "ACTIVE", directorateId: foreignDir.id } });
  const context = { organizationId: org.id, memberId: actor.id };
  let sequence = 0; const email = (label: string) => `${label}-${sequence++}-${suffix}@test.local`;
  try {
    await suite.test("1-5 criação persiste só convite, hash e token com entropia", async () => {
      const invitedEmail = email("creation"); const accounts = await prisma.hubAccount.count(); const members = await prisma.hubMember.count();
      const created = await createHubInvitation(prisma, context, { email: invitedEmail, organizationPosition: "MEMBER", memberCategory: "TRAINEE", directorateId: dir.id });
      const raw = tokenFrom(created); assert.ok(Buffer.from(raw, "base64url").length >= HUB_INVITATION_TOKEN_BYTES); assert.equal(await prisma.hubAccount.count(), accounts); assert.equal(await prisma.hubMember.count(), members);
      const stored = await prisma.hubMemberInvitation.findUniqueOrThrow({ where: { id: created.invitation.id } }); assert.equal(stored.tokenHash, hashHubInvitationToken(raw)); assert.equal(JSON.stringify(stored).includes(raw), false); assert.equal("temporaryPassword" in created, false);
    });
    await suite.test("6 convite pendente duplicado é rejeitado", async () => { const value = email("duplicate"); await createHubInvitation(prisma, context, { email: value, organizationPosition: "MEMBER", memberCategory: "MEMBER" }); await assert.rejects(() => createHubInvitation(prisma, context, { email: value, organizationPosition: "MEMBER", memberCategory: "MEMBER" }), apiStatus(409)); });
    await suite.test("7 acesso cruzado a convite é genérico", async () => { const created = await createHubInvitation(prisma, context, { email: email("tenant"), organizationPosition: "MEMBER", memberCategory: "MEMBER" }); await assert.rejects(() => revokeHubInvitation(prisma, { organizationId: foreignOrg.id, memberId: foreign.id }, created.invitation.id), apiStatus(404)); });
    await suite.test("8 Diretoria inativa é rejeitada", async () => { await prisma.hubDirectorate.update({ where: { id: otherDir.id }, data: { isActive: false } }); await assert.rejects(() => createHubInvitation(prisma, context, { email: email("inactive-dir"), organizationPosition: "MEMBER", memberCategory: "MEMBER", directorateId: otherDir.id }), apiStatus(404)); await prisma.hubDirectorate.update({ where: { id: otherDir.id }, data: { isActive: true } }); });
    await suite.test("9 Presidência exige confirmação explícita", async () => { await assert.rejects(() => createHubInvitation(prisma, context, { email: email("president-confirm"), organizationPosition: "PRESIDENT", memberCategory: "MEMBER" }), apiStatus(422)); });
    await suite.test("10 Presidente e Conselheiro não podem liderar Diretoria", async () => { await assert.rejects(() => createHubInvitation(prisma, context, { email: email("president-director"), organizationPosition: "PRESIDENT", memberCategory: "MEMBER", directorateId: dir.id, appointAsDirector: true, confirmPresidentTransfer: true }), apiStatus(422)); await assert.rejects(() => createHubInvitation(prisma, context, { email: email("counselor-director"), organizationPosition: "COUNSELOR", memberCategory: "MEMBER", directorateId: dir.id, appointAsDirector: true }), apiStatus(422)); });
    await suite.test("11 aceite cria conta, membro ativo e carteira", async () => { const created = await createHubInvitation(prisma, context, { email: email("accept"), organizationPosition: "MEMBER", memberCategory: "TRAINEE", directorateId: dir.id }); const accepted = await acceptHubInvitation(prisma, tokenFrom(created), { fullName: "Pessoa Convidada", password, passwordConfirmation: password }); const acceptedMember = await prisma.hubMember.findUniqueOrThrow({ where: { id: accepted.memberId }, include: { walletAccount: true } }); assert.equal(acceptedMember.status, "ACTIVE"); assert.ok(acceptedMember.walletAccount); });
    await suite.test("12 nome e senha são validados", async () => { const created = await createHubInvitation(prisma, context, { email: email("validation"), organizationPosition: "MEMBER", memberCategory: "MEMBER" }); await assert.rejects(() => acceptHubInvitation(prisma, tokenFrom(created), { fullName: "", password: "fraca", passwordConfirmation: "fraca" }), apiStatus(422)); });
    await suite.test("13 confirmação divergente é rejeitada", async () => { const created = await createHubInvitation(prisma, context, { email: email("confirmation"), organizationPosition: "MEMBER", memberCategory: "MEMBER" }); await assert.rejects(() => acceptHubInvitation(prisma, tokenFrom(created), { fullName: "Nome Completo", password, passwordConfirmation: `${password}x` }), apiStatus(422)); });
    await suite.test("14 token expirado retorna 410", async () => { const created = await createHubInvitation(prisma, context, { email: email("expired"), organizationPosition: "MEMBER", memberCategory: "MEMBER" }); await prisma.hubMemberInvitation.update({ where: { id: created.invitation.id }, data: { expiresAt: new Date(0) } }); await assert.rejects(() => previewHubInvitation(prisma, tokenFrom(created)), apiStatus(410)); });
    await suite.test("15 token revogado retorna 410", async () => { const created = await createHubInvitation(prisma, context, { email: email("revoked"), organizationPosition: "MEMBER", memberCategory: "MEMBER" }); const raw = tokenFrom(created); await revokeHubInvitation(prisma, context, created.invitation.id); await assert.rejects(() => previewHubInvitation(prisma, raw), apiStatus(410)); });
    await suite.test("16 token inválido não revela organização", async () => { await assert.rejects(() => previewHubInvitation(prisma, "invalid-token-that-does-not-exist-000000000"), (error: unknown) => error instanceof HubApiError && error.status === 404 && !error.message.includes(org.name)); });
    await suite.test("17 token aceito é de uso único", async () => { const created = await createHubInvitation(prisma, context, { email: email("single-use"), organizationPosition: "MEMBER", memberCategory: "MEMBER" }); const raw = tokenFrom(created); await acceptHubInvitation(prisma, raw, { fullName: "Uso Único", password, passwordConfirmation: password }); await assert.rejects(() => acceptHubInvitation(prisma, raw, { fullName: "Uso Único", password, passwordConfirmation: password }), apiStatus(410)); });
    await suite.test("18 aceite concorrente cria uma conta e uma participação", async () => { const invitedEmail = email("concurrent"); const created = await createHubInvitation(prisma, context, { email: invitedEmail, organizationPosition: "MEMBER", memberCategory: "MEMBER" }); const raw = tokenFrom(created); const results = await Promise.allSettled([acceptHubInvitation(prisma, raw, { fullName: "Concorrente", password, passwordConfirmation: password }), acceptHubInvitation(prisma, raw, { fullName: "Concorrente", password, passwordConfirmation: password })]); assert.equal(results.filter((item) => item.status === "fulfilled").length, 1); assert.equal(await prisma.hubAccount.count({ where: { normalizedEmail: invitedEmail } }), 1); assert.equal(await prisma.hubMember.count({ where: { organizationId: org.id, normalizedEmail: invitedEmail } }), 1); });
    await suite.test("19-21 conta global existente é reutilizada com autenticação correta", async () => { const existingEmail = email("existing"); const account = await prisma.hubAccount.create({ data: { email: existingEmail, normalizedEmail: existingEmail, passwordHash: await hashHubPassword(password), mustChangePassword: false } }); const otherMembership = await prisma.hubMember.create({ data: { organizationId: foreignOrg.id, accountId: account.id, name: "Existing", email: existingEmail, normalizedEmail: existingEmail, passwordHash: account.passwordHash, status: "ACTIVE" } }); const created = await createHubInvitation(prisma, context, { email: existingEmail, organizationPosition: "MEMBER", memberCategory: "MEMBER" }); const raw = tokenFrom(created); await assert.rejects(() => acceptHubInvitation(prisma, raw, { fullName: "Outra Organização", password: "", passwordConfirmation: "", authenticatedAccountId: actorAccount.id }), apiStatus(401)); const accepted = await acceptHubInvitation(prisma, raw, { fullName: "Outra Organização", password: "", passwordConfirmation: "", authenticatedAccountId: account.id }); assert.equal(accepted.accountId, account.id); assert.equal(await prisma.hubAccount.count({ where: { normalizedEmail: existingEmail } }), 1); assert.ok(await prisma.hubMember.findUnique({ where: { id: otherMembership.id } })); await assert.rejects(() => createHubInvitation(prisma, context, { email: existingEmail, organizationPosition: "MEMBER", memberCategory: "MEMBER" }), apiStatus(409)); });
    await suite.test("22-23 aceite grava lifecycle/audit sem token bruto", async () => { const created = await createHubInvitation(prisma, context, { email: email("audit"), organizationPosition: "MEMBER", memberCategory: "MEMBER" }); const raw = tokenFrom(created); const accepted = await acceptHubInvitation(prisma, raw, { fullName: "Pessoa Auditada", password, passwordConfirmation: password }); assert.ok(await prisma.hubMemberLifecycleEvent.findFirst({ where: { memberId: accepted.memberId, type: "JOINED" } })); const logs = await prisma.hubAuditLog.findMany({ where: { organizationId: org.id, entityId: { in: [created.invitation.id, accepted.memberId] } } }); assert.equal(JSON.stringify(logs).includes(raw), false); });
    await suite.test("24 convite legado é concluído sem duplicar conta ou carteira", async () => { const legacyEmail = email("legacy"); const legacyAccount = await prisma.hubAccount.create({ data: { email: legacyEmail, normalizedEmail: legacyEmail, passwordHash: await hashHubPassword("SenhaTemporaria123"), mustChangePassword: true } }); const legacy = await prisma.hubMember.create({ data: { organizationId: org.id, accountId: legacyAccount.id, name: "Convite legado", email: legacyEmail, normalizedEmail: legacyEmail, passwordHash: legacyAccount.passwordHash, status: "INVITED" } }); await prisma.hubWalletAccount.create({ data: { memberId: legacy.id } }); const secure = await regenerateLegacyHubInvitation(prisma, context, legacy.id); const accepted = await acceptHubInvitation(prisma, tokenFrom(secure), { fullName: "Legado Seguro", password, passwordConfirmation: password }); assert.equal(accepted.memberId, legacy.id); assert.equal(accepted.accountId, legacyAccount.id); assert.equal(await prisma.hubWalletAccount.count({ where: { memberId: legacy.id } }), 1); assert.equal((await prisma.hubMember.findUniqueOrThrow({ where: { id: legacy.id } })).status, "ACTIVE"); });
    await suite.test("24b convite legado de conta compartilhada preserva senha e exige autenticação", async () => { const legacyEmail = email("legacy-shared"); const originalHash = await hashHubPassword(password); const account = await prisma.hubAccount.create({ data: { email: legacyEmail, normalizedEmail: legacyEmail, passwordHash: originalHash, mustChangePassword: false } }); await prisma.hubMember.create({ data: { organizationId: foreignOrg.id, accountId: account.id, name: "Shared Active", email: legacyEmail, normalizedEmail: legacyEmail, passwordHash: originalHash, status: "ACTIVE" } }); const legacy = await prisma.hubMember.create({ data: { organizationId: org.id, accountId: account.id, name: "Shared Invite", email: legacyEmail, normalizedEmail: legacyEmail, passwordHash: originalHash, status: "INVITED" } }); const secure = await regenerateLegacyHubInvitation(prisma, context, legacy.id); assert.equal((await prisma.hubAccount.findUniqueOrThrow({ where: { id: account.id } })).passwordHash, originalHash); const raw = tokenFrom(secure); await assert.rejects(() => acceptHubInvitation(prisma, raw, { fullName: "Shared Secure", password: "", passwordConfirmation: "" }), apiStatus(401)); await acceptHubInvitation(prisma, raw, { fullName: "Shared Secure", password: "", passwordConfirmation: "", authenticatedAccountId: account.id }); assert.equal((await prisma.hubAccount.findUniqueOrThrow({ where: { id: account.id } })).passwordHash, originalHash); });
    await suite.test("25-29 Presidência é única e transferida atomicamente", async () => { await assert.rejects(() => prisma.hubMember.create({ data: { organizationId: org.id, name: "Segundo", email: email("second-president"), normalizedEmail: email("unused"), passwordHash: "test", status: "ACTIVE", organizationPosition: "PRESIDENT" } })); const target = await prisma.hubMember.create({ data: { organizationId: org.id, name: "Target", email: email("target"), normalizedEmail: email("target-normalized"), passwordHash: "test", status: "ACTIVE", directorateId: dir.id } }); await transferHubPresidency(prisma, context, target.id); assert.equal((await prisma.hubMember.findUniqueOrThrow({ where: { id: actor.id } })).organizationPosition, "MEMBER"); assert.equal((await prisma.hubMember.findUniqueOrThrow({ where: { id: target.id } })).organizationPosition, "PRESIDENT"); assert.equal(await prisma.hubMember.count({ where: { organizationId: org.id, status: "ACTIVE", organizationPosition: "PRESIDENT" } }), 1); await transferHubPresidency(prisma, { organizationId: org.id, memberId: target.id }, actor.id); const invited = await createHubInvitation(prisma, context, { email: email("president-invite"), organizationPosition: "PRESIDENT", memberCategory: "MEMBER", confirmPresidentTransfer: true }); assert.equal((await prisma.hubMember.findUniqueOrThrow({ where: { id: actor.id } })).organizationPosition, "PRESIDENT"); await acceptHubInvitation(prisma, tokenFrom(invited), { fullName: "Nova Presidência", password, passwordConfirmation: password }); assert.equal(await prisma.hubMember.count({ where: { organizationId: org.id, status: "ACTIVE", organizationPosition: "PRESIDENT" } }), 1); });
    await suite.test("27 transferências concorrentes preservam uma Presidência", async () => { const currentPresident = await prisma.hubMember.findFirstOrThrow({ where: { organizationId: org.id, status: "ACTIVE", organizationPosition: "PRESIDENT" } }); const first = await prisma.hubMember.create({ data: { organizationId: org.id, name: "Concurrent A", email: email("president-a"), normalizedEmail: email("president-a-normalized"), passwordHash: "test", status: "ACTIVE" } }); const second = await prisma.hubMember.create({ data: { organizationId: org.id, name: "Concurrent B", email: email("president-b"), normalizedEmail: email("president-b-normalized"), passwordHash: "test", status: "ACTIVE" } }); await Promise.allSettled([transferHubPresidency(prisma, { organizationId: org.id, memberId: currentPresident.id }, first.id), transferHubPresidency(prisma, { organizationId: org.id, memberId: currentPresident.id }, second.id)]); assert.equal(await prisma.hubMember.count({ where: { organizationId: org.id, status: "ACTIVE", organizationPosition: "PRESIDENT" } }), 1); });
    await suite.test("30 último administrador de Ajustes não perde acesso por rota comum", async () => { const soloOrg = await prisma.hubOrganization.create({ data: { name: `Solo ${suffix}`, hubName: "Solo", slug: `solo-${suffix}` } }); const solo = await prisma.hubMember.create({ data: { organizationId: soloOrg.id, name: "Solo", email: email("solo"), normalizedEmail: email("solo-normalized"), passwordHash: "test", status: "ACTIVE", organizationPosition: "COUNSELOR" } }); await assert.rejects(() => updateHubMemberClassification(prisma, { organizationId: soloOrg.id, memberId: solo.id }, solo.id, { organizationPosition: "MEMBER", memberCategory: "MEMBER" }), apiStatus(409)); await prisma.hubOrganization.delete({ where: { id: soloOrg.id } }); });
    await suite.test("31-38 liderança de Diretoria valida elegibilidade e movimentação", async () => { const wrongDir = await prisma.hubMember.create({ data: { organizationId: org.id, name: "Wrong Dir", email: email("wrong-dir"), normalizedEmail: email("wrong-dir-normalized"), passwordHash: "test", status: "ACTIVE", directorateId: otherDir.id } }); await assert.rejects(() => updateHubDirectorateLeadership(prisma, context, dir.id, wrongDir.id), apiStatus(422)); await assert.rejects(() => updateHubDirectorateLeadership(prisma, context, dir.id, actor.id), apiStatus(422)); await assert.rejects(() => updateHubDirectorateLeadership(prisma, context, dir.id, counselor.id), apiStatus(422)); const inactive = await prisma.hubMember.create({ data: { organizationId: org.id, name: "Inactive", email: email("inactive"), normalizedEmail: email("inactive-normalized"), passwordHash: "test", status: "DISABLED", directorateId: dir.id } }); await assert.rejects(() => updateHubDirectorateLeadership(prisma, context, dir.id, inactive.id), apiStatus(422)); await assert.rejects(() => updateHubDirectorateLeadership(prisma, context, dir.id, foreign.id), apiStatus(404)); const led = await updateHubDirectorateLeadership(prisma, context, dir.id, member.id); assert.equal(led.directorId, member.id); const replacement = await prisma.hubMember.create({ data: { organizationId: org.id, name: "Replacement", email: email("replacement"), normalizedEmail: email("replacement-normalized"), passwordHash: "test", status: "ACTIVE", directorateId: dir.id } }); await updateHubDirectorateLeadership(prisma, context, dir.id, replacement.id); assert.equal((await prisma.hubMember.findUniqueOrThrow({ where: { id: member.id } })).status, "ACTIVE"); });
    await suite.test("39-44 resolver usa Diretoria atual e respeita preferência explícita", async () => { await prisma.hubMember.update({ where: { id: member.id }, data: { directorateId: dir.id } }); assert.equal((await resolveHubDashboardScope(prisma, member.id, undefined)).scope, "directorate"); assert.equal((await resolveHubDashboardScope(prisma, member.id, "organization")).scope, "organization"); assert.equal((await resolveHubDashboardScope(prisma, member.id, "directorate")).scope, "directorate"); await prisma.hubMember.update({ where: { id: member.id }, data: { directorateId: otherDir.id } }); assert.equal((await resolveHubDashboardScope(prisma, member.id, undefined)).directorateName, otherDir.name); await prisma.hubMember.update({ where: { id: member.id }, data: { directorateId: null } }); assert.equal((await resolveHubDashboardScope(prisma, member.id, undefined)).scope, "organization"); assert.equal((await resolveHubDashboardScope(prisma, actor.id, undefined)).scope, "organization"); });
    await suite.test("45-47 Home não expõe nem renderiza finanças", async () => { const service = await readFile(path.join(process.cwd(), "src/lib/hub/dashboard-service.ts"), "utf8"); const component = await readFile(path.join(process.cwd(), "src/components/hub/HubDashboardCore.tsx"), "utf8"); for (const forbidden of ["currentBalanceCents", "entriesMonthCents", "expensesMonthCents"]) assert.equal(service.includes(forbidden), false); for (const forbidden of ["Saldo atual", "CircleDollarSign", "useHubDisplay", "R$", "entriesMonthCents", "expensesMonthCents"]) assert.equal(component.includes(forbidden), false); });
    await suite.test("48-50 integridade de fonte e migração", async () => { const settings = await readFile(path.join(process.cwd(), "src/lib/hub/settings-service.ts"), "utf8"); const ui = await readFile(path.join(process.cwd(), "src/components/hub/HubSettingsPage.tsx"), "utf8"); const migration = await readFile(path.join(process.cwd(), "prisma/migrations/20260721010000_complete_hub_invitations_governance/migration.sql"), "utf8"); assert.equal(settings.includes("generateHubTemporaryPassword"), false); assert.equal(/\b(confirm|prompt)\s*\(/.test(ui), false); assert.match(migration, /HubMemberInvitation_pending_email_key/); assert.match(migration, /EconomikMember_one_active_president_key/); });
    const snapshot = await getHubSettings(prisma, org.id); assert.equal(snapshot.members.some((item) => item.id === foreign.id), false); assert.equal(snapshot.directorates.some((item) => item.id === foreignDir.id), false);
  } finally { await prisma.hubMemberLifecycleEvent.deleteMany({ where: { organizationId: { in: [org.id, foreignOrg.id] } } }); await prisma.hubAuditLog.deleteMany({ where: { organizationId: { in: [org.id, foreignOrg.id] } } }); await prisma.hubDirectorate.updateMany({ where: { organizationId: { in: [org.id, foreignOrg.id] } }, data: { directorId: null } }); await prisma.hubOrganization.deleteMany({ where: { id: { in: [org.id, foreignOrg.id] } } }); await prisma.hubAccount.deleteMany({ where: { normalizedEmail: { contains: suffix } } }); await prisma.$disconnect(); }
});
