import assert from "node:assert/strict";
import test, { after, before } from "node:test";
import { PrismaClient, type HubRole } from "@prisma/client";
import { createHubNotifications } from "./notifications";
import { growthDirectorateScope, hubStrategyGrowthPolicy, strategicDirectorateScope, type HubStrategicGrowthActor } from "./strategy-growth-policy";
import { handleGrowthMutation } from "./strategy-growth-handlers";
import { acceptProposal, addOpportunityActivity, approveProposal, cancelOpportunity, cancelOpportunityActivity, cancelProposal, closeStrategicReview, configurePipeline, convertLead, createGrowthContact, createGrowthOrganization, createKeyResult, createLead, createOpportunity, createPartnership, createProjectFromOpportunity, createProjectFromProposal, createProposal, createProposalRevision, createStrategicIndicator, createStrategicInitiative, createStrategicObjective, createStrategicReview, createStrategicRisk, createStrategyCycle, expireProposal, keyResultProgress, listGrowthOrganizations, moveOpportunity, recordIndicatorMeasurement, rejectProposal, requestProposalReview, riskScore, sendProposal, transitionStrategyCycle, updateKeyResultValue, updateLeadStatus, updateOpportunity, updatePartnership, updateStrategicObjective, updateStrategicRisk } from "./strategy-growth-service";

const databaseUrl = process.env.ATLAS_HUB_TEST_DATABASE_URL;
if (!databaseUrl) throw new Error("ATLAS_HUB_TEST_DATABASE_URL e obrigatoria para os testes de estrategia e crescimento.");
const prisma = new PrismaClient({ datasourceUrl: databaseUrl });
const tag = `sg-${Date.now()}-${Math.random().toString(36).slice(2)}`;
let orgA = "", orgB = "", dirA = "", dirB = "", foreignDir = "", adminA: HubStrategicGrowthActor, adminA2: HubStrategicGrowthActor, directorA: HubStrategicGrowthActor, directorB: HubStrategicGrowthActor, memberA: HubStrategicGrowthActor, foreignAdmin: HubStrategicGrowthActor, foreignMember: HubStrategicGrowthActor;
let cycleId = "", objectiveId = "", keyResultId = "", indicatorId = "", riskId = "", externalId = "", leadId = "", opportunityId = "", proposalId = "", partnershipId = "";
let openStageId = "", proposalStageId = "", wonStageId = "", lostStageId = "";
let walletBalance = 0, financialCount = 0, approvedProjectId = "", approvedProjectSnapshot = "";

async function member(organizationId: string, name: string, role: HubRole, directorateId?: string): Promise<HubStrategicGrowthActor> {
  const row = await prisma.hubMember.create({ data: { organizationId, name, email: `${tag}-${name}@example.test`, normalizedEmail: `${tag}-${name}@example.test`, passwordHash: "test", role, status: "ACTIVE", mustChangePassword: false, directorateId } });
  return { id: row.id, organizationId, role, directorateId: row.directorateId };
}

before(async () => {
  const [a, b] = await Promise.all([prisma.hubOrganization.create({ data: { name: `${tag}-a`, hubName: tag, slug: `${tag}-a`, timezone: "America/Fortaleza", currency: "BRL" } }), prisma.hubOrganization.create({ data: { name: `${tag}-b`, hubName: tag, slug: `${tag}-b`, timezone: "America/Sao_Paulo", currency: "BRL" } })]); orgA = a.id; orgB = b.id;
  dirA = (await prisma.hubDirectorate.create({ data: { organizationId: orgA, name: "Comercial", slug: `${tag}-comercial` } })).id; dirB = (await prisma.hubDirectorate.create({ data: { organizationId: orgA, name: "Operacoes", slug: `${tag}-operacoes` } })).id; foreignDir = (await prisma.hubDirectorate.create({ data: { organizationId: orgB, name: "Externa", slug: `${tag}-externa` } })).id;
  [adminA, adminA2, directorA, directorB, memberA] = await Promise.all([member(orgA, "admin", "ADMIN"), member(orgA, "admin2", "ADMIN"), member(orgA, "director-a", "DIRECTOR", dirA), member(orgA, "director-b", "DIRECTOR", dirB), member(orgA, "member", "MEMBER", dirA)]);
  [foreignAdmin, foreignMember] = await Promise.all([member(orgB, "foreign-admin", "ADMIN", foreignDir), member(orgB, "foreign-member", "MEMBER", foreignDir)]);
  const account = await prisma.hubWalletAccount.create({ data: { memberId: memberA.id, balanceCents: 123456 } }); walletBalance = account.balanceCents;
  const project = await prisma.hubProject.create({ data: { organizationId: orgA, title: "Historico aprovado", grossAmountCents: 99900, status: "APPROVED", approvedAt: new Date(), approvedMemberPoolCents: 1000, financialRuleSnapshot: { member: 1 } } }); approvedProjectId = project.id; approvedProjectSnapshot = JSON.stringify(project);
  financialCount = await prisma.hubFinancialEntry.count({ where: { organizationId: orgA } });
});

after(async () => { await prisma.hubOrganization.deleteMany({ where: { id: { in: [orgA, orgB] } } }); await prisma.$disconnect(); });

async function freshOpportunity(actor = directorA) {
  return createOpportunity(prisma, actor, { growthOrganizationId: externalId, stageId: openStageId, title: `Oportunidade ${crypto.randomUUID()}`, source: "OTHER", directorateId: actor.directorateId, ownerMemberId: actor.id });
}

async function freshApprovedProposal(validUntil = "2027-12-31") {
  const opportunity = await freshOpportunity(adminA);
  let proposal = await createProposal(prisma, adminA, { opportunityId: opportunity.id, title: `Proposta ${crypto.randomUUID()}`, validUntil });
  await createProposalRevision(prisma, adminA, proposal.id, { scope: "Escopo", deliverables: "Entrega", timeline: "Prazo", commercialTerms: "Termos", items: [{ description: "Item", quantity: 1, unitAmountCents: 1000 }] });
  proposal = await prisma.hubProposal.findUniqueOrThrow({ where: { id: proposal.id } });
  proposal = await requestProposalReview(prisma, adminA, proposal.id, proposal.version);
  return { opportunity, proposal: await approveProposal(prisma, adminA2, proposal.id, proposal.version) };
}

test("1 strategy tenant isolation", async () => { const cycle = await createStrategyCycle(prisma, adminA, { name: "Plano principal", startsAt: "2026-01-01", endsAt: "2026-12-31" }); cycleId = cycle.id; assert.equal(await prisma.hubStrategyCycle.count({ where: { id: cycle.id, organizationId: orgB } }), 0); });
test("2 directorate objective isolation", async () => { const objective = await createStrategicObjective(prisma, directorA, { cycleId, title: "Crescer diretoria", directorateId: dirA, ownerMemberId: directorA.id }); objectiveId = objective.id; assert.equal(hubStrategyGrowthPolicy.canManageObjective(directorB, objective), false); assert.equal(hubStrategyGrowthPolicy.canManageObjective(directorA, objective), true); });
test("3 cycle status concurrency", async () => { const active = await transitionStrategyCycle(prisma, adminA, cycleId, { status: "ACTIVE", version: 1 }); assert.equal(active.version, 2); await assert.rejects(() => transitionStrategyCycle(prisma, adminA, cycleId, { status: "CLOSED", version: 1 }), (error: unknown) => (error as { status?: number }).status === 409); });
test("4 stale objective update", async () => { const updated = await updateStrategicObjective(prisma, directorA, objectiveId, { version: 1, status: "ACTIVE", progress: 10 }); assert.equal(updated.version, 2); await assert.rejects(() => updateStrategicObjective(prisma, directorA, objectiveId, { version: 1, progress: 20 }), (error: unknown) => (error as { status?: number }).status === 409); });
test("5 key-result direction calculation", () => { assert.equal(keyResultProgress("INCREASE", 0, 100, 50), 50); assert.equal(keyResultProgress("DECREASE", 100, 0, 50), 50); assert.equal(keyResultProgress("MAINTAIN", 100, 100, 100), 100); });
test("6 key-result history", async () => { const kr = await createKeyResult(prisma, directorA, { objectiveId, title: "Receita", unit: "BRL", startValue: 0, targetValue: 100, currentValue: 0, direction: "INCREASE", weight: 100, ownerMemberId: memberA.id }); keyResultId = kr.id; await updateKeyResultValue(prisma, memberA, kr.id, { version: 1, value: 25, notes: "Primeiro fechamento" }); const history = await prisma.hubKeyResultHistory.findMany({ where: { keyResultId: kr.id } }); assert.equal(history.length, 1); assert.equal(Number(history[0].previousValue), 0); assert.equal(Number(history[0].value), 25); });
test("7 indicator append-only measurements", async () => { const indicator = await createStrategicIndicator(prisma, directorA, { name: `Conversao ${tag}`, unit: "%", targetValue: 30, direction: "INCREASE", frequency: "MONTHLY", directorateId: dirA }); indicatorId = indicator.id; await recordIndicatorMeasurement(prisma, directorA, indicator.id, { value: 10, measuredAt: "2026-07-01T12:00:00Z", idempotencyKey: `${tag}-m1` }); await recordIndicatorMeasurement(prisma, directorA, indicator.id, { value: 12, measuredAt: "2026-07-02T12:00:00Z", idempotencyKey: `${tag}-m2` }); assert.equal(await prisma.hubIndicatorMeasurement.count({ where: { indicatorId: indicator.id } }), 2); });
test("8 risk-score derivation", async () => { assert.equal(riskScore(4, 5), 20); const risk = await createStrategicRisk(prisma, directorA, { cycleId, title: "Dependencia", category: "Operacional", probability: 4, impact: 5, directorateId: dirA, mitigation: "Plano B" }); riskId = risk.id; assert.equal(risk.score, 20); });
test("9 archived-cycle immutability", async () => { const cycle = await createStrategyCycle(prisma, adminA, { name: "Arquivavel", startsAt: "2024-01-01", endsAt: "2024-12-31" }); await transitionStrategyCycle(prisma, adminA, cycle.id, { status: "ARCHIVED", version: 1 }); await assert.rejects(() => createStrategicObjective(prisma, adminA, { cycleId: cycle.id, title: "Nao permitido" }), (error: unknown) => (error as { status?: number }).status === 409); });
test("10 review snapshot integrity", async () => { const review = await createStrategicReview(prisma, adminA, { cycleId, reviewDate: "2026-07-20", summary: "Revisao mensal" }); const closed = await closeStrategicReview(prisma, adminA, review.id, 1); assert.equal(closed.status, "CLOSED"); const snapshots = closed.objectiveSnapshots as Array<{ id: string; progress: number }>; assert.ok(snapshots.some((item) => item.id === objectiveId)); const original = JSON.stringify(closed.objectiveSnapshots); await updateStrategicObjective(prisma, directorA, objectiveId, { version: 3, progress: 40 }); assert.equal(JSON.stringify((await prisma.hubStrategicReview.findUniqueOrThrow({ where: { id: review.id } })).objectiveSnapshots), original); });
test("11 contact privacy", async () => { const external = await createGrowthOrganization(prisma, adminA, { name: `Empresa ${tag}`, website: "https://example.com", industry: "Tecnologia" }); externalId = external.id; await createGrowthContact(prisma, adminA, { growthOrganizationId: external.id, name: "Contato", email: `${tag}@example.com`, phone: "85999999999" }); const adminList = await listGrowthOrganizations(prisma, adminA); const memberList = await listGrowthOrganizations(prisma, memberA); assert.ok("contacts" in adminList[0]); assert.equal("contacts" in memberList[0], false); assert.equal("document" in memberList[0], false); });
test("12 lead conversion idempotency", async () => { await configurePipeline(prisma, adminA, [{ name: "Qualificacao", probability: 20 }, { name: "Proposta", probability: 60 }, { name: "Ganha", probability: 100, isWon: true }, { name: "Perdida", probability: 0, isLost: true }]); const stages = await prisma.hubPipelineStage.findMany({ where: { organizationId: orgA } }); openStageId = stages.find((s) => s.name === "Qualificacao")!.id; proposalStageId = stages.find((s) => s.name === "Proposta")!.id; wonStageId = stages.find((s) => s.isWon)!.id; lostStageId = stages.find((s) => s.isLost)!.id; const lead = await createLead(prisma, directorA, { title: "Lead principal", source: "REFERRAL", growthOrganizationId: externalId, idempotencyKey: `${tag}-lead` }); leadId = lead.id; const qualified = await updateLeadStatus(prisma, directorA, lead.id, { version: 1, status: "QUALIFYING" }); await updateLeadStatus(prisma, directorA, lead.id, { version: qualified.version, status: "QUALIFIED" }); const payload = { stageId: openStageId, growthOrganizationId: externalId, estimatedValueCents: 50000, idempotencyKey: `${tag}-convert` }; const first = await convertLead(prisma, directorA, lead.id, payload); const second = await convertLead(prisma, directorA, lead.id, payload); opportunityId = first.id; assert.equal(second.id, first.id); });
test("13 duplicate conversion with different payload", async () => { await assert.rejects(() => convertLead(prisma, directorA, leadId, { stageId: openStageId, growthOrganizationId: externalId, estimatedValueCents: 99999, idempotencyKey: `${tag}-convert` }), (error: unknown) => (error as { status?: number }).status === 409); });
test("14 pipeline ordering", async () => { const stages = await prisma.hubPipelineStage.findMany({ where: { organizationId: orgA, isActive: true }, orderBy: { order: "asc" } }); assert.deepEqual(stages.map((stage) => stage.order), [1, 2, 3, 4]); });
test("15 won/lost stage uniqueness", async () => { await assert.rejects(() => configurePipeline(prisma, adminA, [{ name: "Aberta", probability: 10 }, { name: "Ganha 1", probability: 100, isWon: true }, { name: "Ganha 2", probability: 100, isWon: true }, { name: "Perdida", probability: 0, isLost: true }]), (error: unknown) => (error as { status?: number }).status === 400); });
test("16 opportunity tenant isolation", async () => { const opportunity = await prisma.hubOpportunity.findUniqueOrThrow({ where: { id: opportunityId } }); const foreign: HubStrategicGrowthActor = { ...adminA, organizationId: orgB }; assert.equal(hubStrategyGrowthPolicy.canAccessOpportunity(foreign, opportunity), false); });
test("17 directorate opportunity isolation", async () => { const opportunity = await prisma.hubOpportunity.findUniqueOrThrow({ where: { id: opportunityId } }); assert.equal(hubStrategyGrowthPolicy.canAccessOpportunity(directorB, opportunity), false); assert.equal(hubStrategyGrowthPolicy.canAccessOpportunity(directorA, opportunity), true); });
test("18 stage movement concurrency", async () => { const opportunity = await prisma.hubOpportunity.findUniqueOrThrow({ where: { id: opportunityId } }); const moved = await moveOpportunity(prisma, directorA, opportunity.id, { stageId: proposalStageId, version: opportunity.version }); assert.equal(moved.stageId, proposalStageId); await assert.rejects(() => moveOpportunity(prisma, directorA, opportunity.id, { stageId: openStageId, version: opportunity.version }), (error: unknown) => (error as { status?: number }).status === 409); });
test("19 opportunity loss reason", async () => { const opportunity = await prisma.hubOpportunity.findUniqueOrThrow({ where: { id: opportunityId } }); await assert.rejects(() => moveOpportunity(prisma, directorA, opportunity.id, { stageId: lostStageId, version: opportunity.version, confirm: true }), /Motivo interno/); });
test("20 opportunity win confirmation", async () => { const opportunity = await prisma.hubOpportunity.findUniqueOrThrow({ where: { id: opportunityId } }); await assert.rejects(() => moveOpportunity(prisma, directorA, opportunity.id, { stageId: wonStageId, version: opportunity.version }), (error: unknown) => (error as { status?: number }).status === 409); await moveOpportunity(prisma, directorA, opportunity.id, { stageId: wonStageId, version: opportunity.version, confirm: true }); });
test("21 one project created from one opportunity", async () => { const payload = { confirm: true, idempotencyKey: `${tag}-opp-project` }; const first = await createProjectFromOpportunity(prisma, directorA, opportunityId, payload); const second = await createProjectFromOpportunity(prisma, directorA, opportunityId, payload); assert.equal(first.id, second.id); assert.equal(await prisma.hubProject.count({ where: { idempotencyKey: `opportunity:${opportunityId}` } }), 1); });
test("22 financial entries remain unchanged", async () => { assert.equal(await prisma.hubFinancialEntry.count({ where: { organizationId: orgA } }), financialCount); });
test("23 proposal total calculation", async () => { const proposal = await createProposal(prisma, adminA, { opportunityId, title: "Proposta principal", validUntil: "2026-12-31" }); proposalId = proposal.id; await createProposalRevision(prisma, adminA, proposal.id, { scope: "Escopo", deliverables: "Entregas", timeline: "30 dias", commercialTerms: "Pagamento acordado", discountCents: 500, items: [{ description: "Servico", quantity: 2, unitAmountCents: 10000 }] }); const updated = await prisma.hubProposal.findUniqueOrThrow({ where: { id: proposal.id } }); assert.equal(updated.subtotalCents, 20000); assert.equal(updated.totalCents, 19500); });
test("24 proposal revision immutability", async () => { let proposal = await prisma.hubProposal.findUniqueOrThrow({ where: { id: proposalId } }); proposal = await requestProposalReview(prisma, adminA, proposal.id, proposal.version); const approved = await approveProposal(prisma, adminA2, proposal.id, proposal.version); assert.equal(approved.status, "APPROVED"); await assert.rejects(() => createProposalRevision(prisma, adminA, proposalId, { scope: "Novo", deliverables: "Novo", timeline: "Novo", commercialTerms: "Novo", items: [{ description: "Outro", quantity: 1, unitAmountCents: 1 }] }), (error: unknown) => (error as { status?: number }).status === 409); });
test("25 proposal author self-approval rejection", async () => { const proposal = await createProposal(prisma, adminA, { opportunityId, title: "Autoaprovacao" }); await createProposalRevision(prisma, adminA, proposal.id, { scope: "Escopo", deliverables: "Entrega", timeline: "Prazo", commercialTerms: "Termos", items: [{ description: "Item", quantity: 1, unitAmountCents: 100 }] }); const review = await requestProposalReview(prisma, adminA, proposal.id, 2); await assert.rejects(() => approveProposal(prisma, adminA, proposal.id, review.version), (error: unknown) => (error as { status?: number }).status === 403); });
test("26 proposal acceptance race", async () => { const proposal = await prisma.hubProposal.findUniqueOrThrow({ where: { id: proposalId } }); const results = await Promise.allSettled([acceptProposal(prisma, adminA2, proposal.id, { version: proposal.version, confirm: true }), acceptProposal(prisma, adminA2, proposal.id, { version: proposal.version, confirm: true })]); assert.ok(results.some((result) => result.status === "fulfilled")); assert.equal((await prisma.hubProposal.findUniqueOrThrow({ where: { id: proposal.id } })).status, "ACCEPTED"); });
test("27 one project created from accepted proposal", async () => { const before = await prisma.hubProject.count({ where: { organizationId: orgA } }); const payload = { confirm: true, idempotencyKey: `${tag}-proposal-project` }; const first = await createProjectFromProposal(prisma, adminA2, proposalId, payload); const second = await createProjectFromProposal(prisma, adminA2, proposalId, payload); assert.equal(first.id, second.id); assert.equal(await prisma.hubProject.count({ where: { organizationId: orgA } }), before); assert.equal((await prisma.hubProposal.findUniqueOrThrow({ where: { id: proposalId } })).projectId, first.id); });
test("28 partnership optimistic concurrency", async () => { const partnership = await createPartnership(prisma, directorA, { growthOrganizationId: externalId, title: "Parceria", type: "INSTITUCIONAL", goals: "Crescer" }); partnershipId = partnership.id; const updated = await updatePartnership(prisma, directorA, partnership.id, { version: 1, status: "ACTIVE" }); assert.equal(updated.version, 2); await assert.rejects(() => updatePartnership(prisma, directorA, partnership.id, { version: 1, status: "PAUSED" }), (error: unknown) => (error as { status?: number }).status === 409); });
test("29 dashboard permission filtering", async () => { const strategyScope = strategicDirectorateScope(directorA); const growthScope = growthDirectorateScope(directorA); assert.deepEqual(strategyScope, { OR: [{ directorateId: dirA }, { directorateId: null }] }); const ownCount = await prisma.hubOpportunity.count({ where: { organizationId: orgA, ...growthScope } }); const foreignDirectorate = await createOpportunity(prisma, directorB, { growthOrganizationId: externalId, stageId: openStageId, title: "Outra diretoria", source: "OTHER" }); assert.equal(await prisma.hubOpportunity.count({ where: { organizationId: orgA, ...growthScope } }), ownCount); assert.equal(hubStrategyGrowthPolicy.canAccessOpportunity(directorA, foreignDirectorate), false); });
test("30 notification privacy", async () => { await prisma.$transaction(async (tx) => { await createHubNotifications(tx, [{ organizationId: orgA, recipientMemberId: memberA.id, actorMemberId: adminA.id, type: "OPPORTUNITY_STAGE_CHANGED", title: "Etapa alterada", body: "Uma oportunidade mudou de etapa.", href: `/hub/crescimento/oportunidades?id=${opportunityId}`, entityType: "OPPORTUNITY", entityId: opportunityId, idempotencyKey: `${tag}-privacy` }]); }); const notification = await prisma.hubNotification.findFirstOrThrow({ where: { organizationId: orgA, idempotencyKey: `${tag}-privacy` } }); assert.equal(notification.body.includes("@"), false); assert.equal(notification.body.includes("859"), false); assert.equal(notification.body.toLowerCase().includes("perda"), false); });
test("31 wallet balances unchanged", async () => { assert.equal((await prisma.hubWalletAccount.findUniqueOrThrow({ where: { memberId: memberA.id } })).balanceCents, walletBalance); });
test("32 approved historical projects unchanged", async () => { assert.equal(JSON.stringify(await prisma.hubProject.findUniqueOrThrow({ where: { id: approvedProjectId } })), approvedProjectSnapshot); });
test("33 no Hub integration test skips", async () => { const tables = await prisma.$queryRaw<Array<{ strategy: boolean; growth: boolean }>>`SELECT to_regclass('public."HubStrategyCycle"') IS NOT NULL AS strategy, to_regclass('public."HubOpportunity"') IS NOT NULL AS growth`; assert.deepEqual(tables[0], { strategy: true, growth: true }); assert.ok(databaseUrl); assert.ok(keyResultId && indicatorId && riskId && partnershipId); });
test("34 foreign key-result owner returns generic 404", async () => { await assert.rejects(() => createKeyResult(prisma, directorA, { objectiveId, title: "Invalido", unit: "%", startValue: 0, targetValue: 1, direction: "INCREASE", weight: 1, ownerMemberId: foreignMember.id }), (error: unknown) => (error as { status?: number }).status === 404); });
test("35 foreign objective on initiative returns generic 404", async () => { const foreignCycle = await createStrategyCycle(prisma, foreignAdmin, { name: "Estrangeiro", startsAt: "2026-01-01", endsAt: "2026-12-31" }); const foreignObjective = await createStrategicObjective(prisma, foreignAdmin, { cycleId: foreignCycle.id, title: "Estrangeiro" }); await assert.rejects(() => createStrategicInitiative(prisma, adminA, { title: "Invalida", objectiveId: foreignObjective.id }), (error: unknown) => (error as { status?: number }).status === 404); });
test("36 foreign primary contact returns generic 404", async () => { const foreignOrganization = await createGrowthOrganization(prisma, foreignAdmin, { name: `Externa ${tag}` }); const foreignContact = await createGrowthContact(prisma, foreignAdmin, { growthOrganizationId: foreignOrganization.id, name: "Contato externo" }); await assert.rejects(() => createOpportunity(prisma, adminA, { growthOrganizationId: externalId, primaryContactId: foreignContact.id, stageId: openStageId, title: "Contato invalido", source: "OTHER" }), (error: unknown) => (error as { status?: number }).status === 404); });
test("37 foreign opportunity on partnership returns generic 404", async () => { await configurePipeline(prisma, foreignAdmin, [{ name: "Aberta", probability: 20 }, { name: "Ganha", probability: 100, isWon: true }, { name: "Perdida", probability: 0, isLost: true }]); const foreignOrganization = await prisma.hubGrowthOrganization.findFirstOrThrow({ where: { organizationId: orgB } }); const foreignStage = await prisma.hubPipelineStage.findFirstOrThrow({ where: { organizationId: orgB, isWon: false, isLost: false } }); const foreignOpportunity = await createOpportunity(prisma, foreignAdmin, { growthOrganizationId: foreignOrganization.id, stageId: foreignStage.id, title: "Outra organizacao", source: "OTHER" }); await assert.rejects(() => createPartnership(prisma, adminA, { growthOrganizationId: externalId, title: "Parceria invalida", type: "TESTE", opportunityId: foreignOpportunity.id }), (error: unknown) => (error as { status?: number }).status === 404); });
test("38 director cannot mutate another directorate lead", async () => { const lead = await createLead(prisma, directorA, { title: "Lead diretoria A", source: "OTHER", idempotencyKey: crypto.randomUUID() }); await assert.rejects(() => updateLeadStatus(prisma, directorB, lead.id, { version: lead.version, status: "QUALIFYING" }), (error: unknown) => (error as { status?: number }).status === 403); });
test("39 director cannot create project from another directorate opportunity", async () => { const opportunity = await freshOpportunity(directorA); const won = await moveOpportunity(prisma, directorA, opportunity.id, { stageId: wonStageId, version: opportunity.version, confirm: true }); await assert.rejects(() => createProjectFromOpportunity(prisma, directorB, won.id, { confirm: true, idempotencyKey: crypto.randomUUID() }), (error: unknown) => (error as { status?: number }).status === 403); });
test("40 assigned member uses real growth mutation handler", async () => { const opportunity = await createOpportunity(prisma, adminA, { growthOrganizationId: externalId, stageId: openStageId, title: "Atribuida", source: "OTHER", ownerMemberId: memberA.id, directorateId: dirA }); const updated = await handleGrowthMutation(prisma, memberA, "opportunity-update", opportunity.id, { version: opportunity.version, nextAction: "Retornar contato", nextActionAt: "2026-07-15T09:00" }); assert.equal((updated as { nextAction?: string } | null)?.nextAction, "Retornar contato"); });
test("41 every exposed enum rejects invalid values with 400", async () => { const invalid = (operation: () => Promise<unknown>) => assert.rejects(operation, (error: unknown) => (error as { status?: number }).status === 400); await invalid(() => createStrategicObjective(prisma, adminA, { cycleId, title: "Prioridade", priority: "INVALID" })); await invalid(() => updateStrategicObjective(prisma, directorA, objectiveId, { version: 4, status: "INVALID" })); await invalid(() => createKeyResult(prisma, adminA, { objectiveId, title: "Direcao", unit: "%", startValue: 0, targetValue: 1, weight: 1, direction: "INVALID" })); await invalid(() => createStrategicInitiative(prisma, adminA, { title: "Status", status: "INVALID" })); await invalid(() => createStrategicIndicator(prisma, adminA, { name: `Frequencia ${crypto.randomUUID()}`, unit: "%", targetValue: 1, direction: "INCREASE", frequency: "INVALID" })); await invalid(() => updateStrategicRisk(prisma, directorA, riskId, { version: 1, status: "INVALID" })); await invalid(() => createGrowthOrganization(prisma, adminA, { name: `Status ${crypto.randomUUID()}`, status: "INVALID" })); await invalid(() => createLead(prisma, adminA, { title: "Origem", source: "INVALID", idempotencyKey: crypto.randomUUID() })); const opportunity = await freshOpportunity(adminA); await invalid(() => addOpportunityActivity(prisma, adminA, opportunity.id, { type: "INVALID", title: "Atividade" })); await invalid(() => createPartnership(prisma, adminA, { growthOrganizationId: externalId, title: "Status", type: "TESTE", status: "INVALID" })); });
test("42 Fortaleza local-midnight measurement", async () => { const indicator = await createStrategicIndicator(prisma, adminA, { name: `Meia-noite ${crypto.randomUUID()}`, unit: "un", targetValue: 1, direction: "INCREASE", frequency: "MONTHLY" }); const measurement = await recordIndicatorMeasurement(prisma, adminA, indicator.id, { value: 1, measuredAt: "2026-07-01T00:15", idempotencyKey: crypto.randomUUID() }); assert.equal(measurement.measuredAt.toISOString(), "2026-07-01T03:15:00.000Z"); assert.equal(measurement.periodKey, "2026-07-01"); });
test("43 won/lost stage swap reconciles terminal opportunities and preserves overrides", async () => { const wonOpportunity = await freshOpportunity(adminA); await moveOpportunity(prisma, adminA, wonOpportunity.id, { stageId: wonStageId, version: wonOpportunity.version, confirm: true }); const lostOpportunity = await freshOpportunity(adminA); await moveOpportunity(prisma, adminA, lostOpportunity.id, { stageId: lostStageId, version: lostOpportunity.version, confirm: true, lossReason: "Teste" }); const overrideOpportunity = await freshOpportunity(adminA); await updateOpportunity(prisma, adminA, overrideOpportunity.id, { version: overrideOpportunity.version, probabilityOverride: 77, probabilityOverrideReason: "Avaliacao manual" }); const stages = await prisma.hubPipelineStage.findMany({ where: { organizationId: orgA, isActive: true }, orderBy: { order: "asc" } }); await configurePipeline(prisma, adminA, stages.map((stage) => ({ id: stage.id, version: stage.version, name: stage.name, probability: stage.id === wonStageId ? 0 : stage.id === lostStageId ? 100 : stage.probability + (stage.id === openStageId ? 5 : 0), isWon: stage.id === lostStageId, isLost: stage.id === wonStageId, isActive: true }))); const [wonAfter, lostAfter, overrideAfter] = await Promise.all([prisma.hubOpportunity.findUniqueOrThrow({ where: { id: wonOpportunity.id } }), prisma.hubOpportunity.findUniqueOrThrow({ where: { id: lostOpportunity.id } }), prisma.hubOpportunity.findUniqueOrThrow({ where: { id: overrideOpportunity.id } })]); assert.equal(wonAfter.status, "WON"); assert.equal(wonAfter.stageId, lostStageId); assert.equal(lostAfter.status, "LOST"); assert.equal(lostAfter.stageId, wonStageId); assert.equal(overrideAfter.probability, 77); assert.equal(overrideAfter.probabilityOverride, 77); [wonStageId, lostStageId] = [lostStageId, wonStageId]; });
test("44 stale pipeline configuration returns 409", async () => { const stages = await prisma.hubPipelineStage.findMany({ where: { organizationId: orgA, isActive: true }, orderBy: { order: "asc" } }); await assert.rejects(() => configurePipeline(prisma, adminA, stages.map((stage) => ({ id: stage.id, version: stage.version - 1, name: stage.name, probability: stage.probability, isWon: stage.isWon, isLost: stage.isLost }))), (error: unknown) => (error as { status?: number }).status === 409); });
test("45 lead disqualification reason is audited and not notified", async () => { const lead = await createLead(prisma, directorA, { title: "Desqualificar", source: "OTHER", idempotencyKey: crypto.randomUUID() }); const updated = await updateLeadStatus(prisma, directorA, lead.id, { version: lead.version, status: "DISQUALIFIED", disqualificationReason: "Sem aderencia" }); assert.equal(updated.disqualificationReason, "Sem aderencia"); assert.equal(await prisma.hubNotification.count({ where: { organizationId: orgA, body: { contains: "Sem aderencia" } } }), 0); });
test("46 opportunity cancellation appends history", async () => { const opportunity = await freshOpportunity(adminA); const updated = await cancelOpportunity(prisma, adminA, opportunity.id, { version: opportunity.version, confirm: true, reason: "Prioridade alterada" }); assert.equal(updated.status, "CANCELLED"); assert.ok(updated.cancelledAt); assert.equal(await prisma.hubOpportunityStageHistory.count({ where: { opportunityId: opportunity.id, toStatus: "CANCELLED" } }), 1); });
test("47 activity correction and cancellation markers", async () => { const opportunity = await freshOpportunity(adminA); const first = await addOpportunityActivity(prisma, adminA, opportunity.id, { type: "CALL", title: "Ligacao" }); const correction = await addOpportunityActivity(prisma, adminA, opportunity.id, { type: "CALL", title: "Ligacao corrigida", replacesActivityId: first.id, correctionReason: "Horario incorreto" }); assert.equal(correction.replacesActivityId, first.id); assert.ok((await prisma.hubOpportunityActivity.findUniqueOrThrow({ where: { id: first.id } })).cancelledAt); const cancelled = await cancelOpportunityActivity(prisma, adminA, correction.id, { confirm: true, reason: "Duplicada" }); assert.ok(cancelled.cancelledAt); });
test("48 proposal sent transition", async () => { const { proposal } = await freshApprovedProposal(); const sent = await sendProposal(prisma, adminA2, proposal.id, { version: proposal.version }); assert.equal(sent.status, "SENT"); assert.ok(sent.sentAt); });
test("49 proposal rejection requires reason", async () => { const { proposal } = await freshApprovedProposal(); const sent = await sendProposal(prisma, adminA2, proposal.id, { version: proposal.version }); const rejected = await rejectProposal(prisma, adminA2, sent.id, { version: sent.version, reason: "Condicoes recusadas" }); assert.equal(rejected.status, "REJECTED"); assert.equal(rejected.rejectionReason, "Condicoes recusadas"); });
test("50 proposal expiration uses organization-local date", async () => { const { proposal } = await freshApprovedProposal("2020-01-01"); const expired = await expireProposal(prisma, adminA2, proposal.id, { version: proposal.version }); assert.equal(expired.status, "EXPIRED"); assert.ok(expired.expiredAt); });
test("51 proposal cancellation", async () => { const opportunity = await freshOpportunity(adminA); const proposal = await createProposal(prisma, adminA, { opportunityId: opportunity.id, title: "Cancelar" }); const cancelled = await cancelProposal(prisma, adminA, proposal.id, { version: proposal.version, confirm: true, reason: "Escopo retirado" }); assert.equal(cancelled.status, "CANCELLED"); assert.equal(cancelled.cancellationReason, "Escopo retirado"); });
test("52 proposal acceptance creates opportunity history", async () => { const { opportunity, proposal } = await freshApprovedProposal(); const sent = await sendProposal(prisma, adminA2, proposal.id, { version: proposal.version }); await acceptProposal(prisma, adminA2, sent.id, { version: sent.version, confirm: true, markOpportunityWon: true }); const history = await prisma.hubOpportunityStageHistory.findFirst({ where: { opportunityId: opportunity.id, toStatus: "WON", reason: { contains: proposal.id } } }); assert.ok(history); });
test("53 financial entries remain unchanged after added lifecycles", async () => { assert.equal(await prisma.hubFinancialEntry.count({ where: { organizationId: orgA } }), financialCount); });
test("54 wallet balances remain unchanged after added lifecycles", async () => { assert.equal((await prisma.hubWalletAccount.findUniqueOrThrow({ where: { memberId: memberA.id } })).balanceCents, walletBalance); });
test("55 historical approved projects remain unchanged after added lifecycles", async () => { assert.equal(JSON.stringify(await prisma.hubProject.findUniqueOrThrow({ where: { id: approvedProjectId } })), approvedProjectSnapshot); });
