import { prisma } from "@/lib/prisma";
import { requireHubMember, requireHubPermission } from "@/lib/hub/auth";
import { hubJson, withHubApi } from "@/lib/hub/api";
import { growthDirectorateScope, leadCapabilities, opportunityCapabilities, partnershipCapabilities, proposalCapabilities } from "@/lib/hub/strategy-growth-policy";
import { createGrowthContact, createGrowthOrganization, createLead, createOpportunity, createPartnership, createProposal, listGrowthOrganizations } from "@/lib/hub/strategy-growth-service";

const actor = (session: Awaited<ReturnType<typeof requireHubMember>>) => ({ id: session.memberId, organizationId: session.organizationId, role: session.role, directorateId: session.directorateId });
const localDateKey = (date: Date, timezone: string) => { const parts = new Intl.DateTimeFormat("en", { timeZone: timezone, year: "numeric", month: "2-digit", day: "2-digit" }).formatToParts(date); const values = Object.fromEntries(parts.map((part) => [part.type, part.value])); return `${values.year}-${values.month}-${values.day}`; };

export const GET = withHubApi(async () => {
  const session = await requireHubPermission("growth:access"); const currentActor = actor(session); const scope = growthDirectorateScope(currentActor); const today = new Date(`${localDateKey(new Date(), session.organization.timezone)}T00:00:00.000Z`); const inSevenDays = new Date(today); inSevenDays.setUTCDate(inSevenDays.getUTCDate() + 7);
  const [organizations, leads, stages, opportunities, proposals, partnerships] = await Promise.all([
    listGrowthOrganizations(prisma, currentActor),
    prisma.hubLead.findMany({ where: { organizationId: session.organizationId, ...scope }, select: { id: true, organizationId: true, title: true, source: true, status: true, growthOrganizationId: true, ownerMemberId: true, directorateId: true, disqualificationReason: true, version: true, createdAt: true }, orderBy: { createdAt: "desc" }, take: 200 }),
    prisma.hubPipelineStage.findMany({ where: { organizationId: session.organizationId }, orderBy: { order: "asc" } }),
    prisma.hubOpportunity.findMany({ where: { organizationId: session.organizationId, ...scope }, include: { growthOrganization: { select: { id: true, name: true } }, stage: { select: { id: true, name: true, order: true, probability: true, isWon: true, isLost: true } }, activities: { orderBy: { occurredAt: "desc" }, take: 10 } }, orderBy: { updatedAt: "desc" }, take: 300 }),
    session.permissions.includes("growth:manage-proposals") || session.permissions.includes("growth:create") ? prisma.hubProposal.findMany({ where: { organizationId: session.organizationId, opportunity: scope }, include: { revisions: { orderBy: { revisionNumber: "desc" }, take: 1, include: { items: true } }, opportunity: { select: { organizationId: true, directorateId: true, ownerMemberId: true, title: true } } }, orderBy: { updatedAt: "desc" }, take: 200 }) : Promise.resolve([]),
    prisma.hubPartnership.findMany({ where: { organizationId: session.organizationId }, include: { growthOrganization: { select: { name: true } } }, orderBy: { updatedAt: "desc" }, take: 200 }),
  ]);
  const visibleOpportunities = opportunities.map((item) => ({ ...item, capabilities: opportunityCapabilities(currentActor, item) })); const open = opportunities.filter((item) => item.status === "OPEN"); const won = opportunities.filter((item) => item.status === "WON"); const lost = opportunities.filter((item) => item.status === "LOST");
  return hubJson({ organizations, leads: leads.map((item) => ({ ...item, capabilities: leadCapabilities(currentActor, item) })), stages, opportunities: visibleOpportunities, proposals: proposals.map((item) => ({ ...item, capabilities: proposalCapabilities(currentActor, { organizationId: item.organizationId, directorateId: item.opportunity.directorateId, ownerMemberId: item.opportunity.ownerMemberId, createdById: item.createdById }) })), partnerships: partnerships.map((item) => ({ ...item, capabilities: partnershipCapabilities(currentActor, item) })), dashboard: { leadsByStatus: Object.fromEntries(["NEW", "QUALIFYING", "QUALIFIED", "DISQUALIFIED", "CONVERTED"].map((status) => [status, leads.filter((item) => item.status === status).length])), estimatedPipelineValueCents: open.reduce((sum, item) => sum + item.estimatedValueCents, 0), weightedPipelineValueCents: open.reduce((sum, item) => sum + Math.round(item.estimatedValueCents * item.probability / 100), 0), wonValueCents: won.reduce((sum, item) => sum + item.estimatedValueCents, 0), lostValueCents: lost.reduce((sum, item) => sum + item.estimatedValueCents, 0), conversionRate: won.length + lost.length ? Math.round(won.length * 10000 / (won.length + lost.length)) / 100 : 0, withoutNextAction: open.filter((item) => !item.nextActionAt).length, proposalsAwaitingReview: proposals.filter((item) => item.status === "INTERNAL_REVIEW").length, expiringProposals: proposals.filter((item) => item.validUntil && item.validUntil >= today && item.validUntil <= inSevenDays && !["ACCEPTED", "REJECTED", "CANCELLED"].includes(item.status)).length }, capabilities: { canCreate: session.permissions.includes("growth:create"), canManage: session.permissions.includes("growth:manage"), canManagePipeline: session.permissions.includes("growth:manage-pipeline"), canManageProposals: session.permissions.includes("growth:manage-proposals") || session.permissions.includes("growth:create"), canReadSensitive: session.permissions.includes("growth:read-sensitive") } });
});

export const POST = withHubApi(async (request) => {
  const body = await request.json().catch(() => null) as Record<string, unknown> | null; const action = String(body?.action || ""); const input = (body?.input || {}) as Record<string, unknown>;
  const session = await requireHubMember(); const currentActor = actor(session);
  const result = action === "organization" ? await createGrowthOrganization(prisma, currentActor, input) : action === "contact" ? await createGrowthContact(prisma, currentActor, input) : action === "lead" ? await createLead(prisma, currentActor, input) : action === "opportunity" ? await createOpportunity(prisma, currentActor, input) : action === "proposal" ? await createProposal(prisma, currentActor, input) : action === "partnership" ? await createPartnership(prisma, currentActor, input) : null;
  return result ? hubJson(result, { status: 201 }) : hubJson({ error: "Acao comercial invalida." }, { status: 400 });
});
